# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionMailer::TestCase::Behavior`.
# Please instead update this file by running `bin/tapioca dsl ActionMailer::TestCase::Behavior`.


module ActionMailer::TestCase::Behavior
  include GeneratedInstanceMethods

  mixes_in_class_methods ::ActiveSupport::Testing::ConstantLookup::ClassMethods
  mixes_in_class_methods GeneratedClassMethods

  module GeneratedClassMethods
    def _decoders; end
    def _decoders=(value); end
    def _decoders?; end
    def _mailer_class; end
    def _mailer_class=(value); end
    def _mailer_class?; end
  end

  module GeneratedInstanceMethods
    def _decoders; end
    def _decoders=(value); end
    def _decoders?; end
    def _mailer_class; end
    def _mailer_class=(value); end
    def _mailer_class?; end
  end
end
