# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `colorize` gem.
# Please instead update this file by running `bin/tapioca gem colorize`.


# Gem version
#
# pkg:gem/colorize#lib/colorize/version.rb:6
module Colorize; end

# pkg:gem/colorize#lib/colorize/class_methods.rb:4
module Colorize::ClassMethods
  # Add color alias
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:135
  def add_color_alias(*params); end

  # pkg:gem/colorize#lib/colorize/class_methods.rb:154
  def add_color_code(code, color); end

  # Generate color and on_color method
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:179
  def add_color_method(key); end

  # Check if color exists
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:214
  def check_if_color_available!(color); end

  # Check if color is missing
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:221
  def check_if_color_exist!(color); end

  # Color codes hash
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:150
  def color_codes; end

  # @return [Boolean]
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:225
  def color_exist?(color); end

  # Generate color and on_color methods
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:168
  def color_methods; end

  # Display color samples
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:125
  def color_samples; end

  # Return array of available colors used by colorize
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:111
  def colors; end

  # Property for disable colorization
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:67
  def disable_colorization(value = T.unsafe(nil)); end

  # Setter for disable colorization
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:82
  def disable_colorization=(value); end

  # Property for readline support
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:45
  def enable_readline_support(value = T.unsafe(nil)); end

  # Setter for enable readline support
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:60
  def enable_readline_support=(value); end

  # Mode codes hash
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:161
  def mode_codes; end

  # Return array of available modes used by colorize
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:118
  def modes; end

  # Generate modes methods
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:192
  def modes_methods; end

  # pkg:gem/colorize#lib/colorize/class_methods.rb:202
  def parse_color_alias_params(params); end

  # Property for prevent recolorization
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:89
  def prevent_colors(value = T.unsafe(nil)); end

  # Setter for prevent recolorization
  #
  # pkg:gem/colorize#lib/colorize/class_methods.rb:104
  def prevent_colors=(value); end
end

# pkg:gem/colorize#lib/colorize/errors.rb:4
class Colorize::ColorAlreadyExist < ::StandardError; end

# pkg:gem/colorize#lib/colorize/errors.rb:7
class Colorize::ColorDontExist < ::StandardError; end

# pkg:gem/colorize#lib/colorize/instance_methods.rb:4
module Colorize::InstanceMethods
  # Change color of string
  #
  # Examples:
  #
  #   puts "This is blue".colorize(:blue)
  #   puts "This is light blue".colorize(:light_blue)
  #   puts "This is also blue".colorize(:color => :blue)
  #   puts "This is light blue with red background".colorize(:color => :light_blue, :background => :red)
  #   puts "This is light blue with red background".colorize(:light_blue ).colorize( :background => :red)
  #   puts "This is blue text on red".blue.on_red
  #   puts "This is red on blue".colorize(:red).on_blue
  #   puts "This is red on blue and underline".colorize(:red).on_blue.underline
  #   puts "This is blue text on red".blue.on_red.blink
  #   puts "This is uncolorized".blue.on_red.uncolorize
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:21
  def colorize(params); end

  # Return true if string is colorized
  #
  # @return [Boolean]
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:43
  def colorized?; end

  # Return uncolorized string
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:34
  def uncolorize; end

  private

  # Color for background (offset 10)
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:117
  def background_color(color); end

  # Color for foreground
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:110
  def color(color); end

  # Set color from params symbol
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:99
  def color_from_symbol(match, symbol); end

  # Generate string with escape colors
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:54
  def colorized_string(mode, color, background_color, previous); end

  # Set colors from params hash
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:84
  def colors_from_hash(match, hash); end

  # Set color from params
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:74
  def colors_from_params(match, params); end

  # Set default colors
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:65
  def defaults_colors(match); end

  # Mode
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:124
  def mode(mode); end

  # Require windows libs
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:160
  def require_windows_libs; end

  # Scan for colorized string
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:142
  def scan_for_colors; end

  # Generate regex for color scanner
  #
  # pkg:gem/colorize#lib/colorize/instance_methods.rb:131
  def scan_for_colors_regex; end

  # pkg:gem/colorize#lib/colorize/instance_methods.rb:148
  def split_colors(match); end
end

# pkg:gem/colorize#lib/colorize/version.rb:7
Colorize::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/colorize#lib/colorize.rb:11
class String
  include ::Comparable
  include ::Colorize::InstanceMethods
  extend ::Colorize::ClassMethods
end
