# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dry-cli` gem.
# Please instead update this file by running `bin/tapioca gem dry-cli`.


# Dry
#
# @since 0.1.0
#
# pkg:gem/dry-cli#lib/dry/cli.rb:6
module Dry
  class << self
    # Create a new instance
    #
    # @param registry_or_command [Dry::CLI::Registry, Dry::CLI::Command]
    #   a registry or singular command
    # @param &block [Block] a configuration block for registry
    #
    # @return [Dry::CLI] the new instance
    # @since 0.4.0
    #
    # pkg:gem/dry-cli#lib/dry/cli.rb:230
    def CLI(registry_or_command = T.unsafe(nil), &block); end
  end
end

# General purpose Command Line Interface (CLI) framework for Ruby
#
# @since 0.1.0
# General purpose Command Line Interface (CLI) framework for Ruby
#
# @since 0.1.0
#
# pkg:gem/dry-cli#lib/dry/cli.rb:10
class Dry::CLI
  # Create a new instance
  #
  # @param command_or_registry [Dry::CLI::Registry, Dry::CLI::Command]
  #   a registry or singular command
  # @param &block [Block] a configuration block for registry
  #
  # @return [Dry::CLI] the new instance
  # @since 0.1.0
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:46
  def initialize(command_or_registry = T.unsafe(nil), &block); end

  # Invoke the CLI
  #
  # @param arguments [Array<string>] the command line arguments (defaults to `ARGV`)
  # @param out [IO] the standard output (defaults to `$stdout`)
  # @param err [IO] the error output (defaults to `$stderr`)
  #
  # @since 0.1.0
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:64
  def call(arguments: T.unsafe(nil), out: T.unsafe(nil), err: T.unsafe(nil)); end

  private

  # Generates registry in runtime
  #
  # @param &block [Block] configuration for the registry
  #
  # @return [Module] module extended with registry abilities and configured with a block
  #
  # @since 0.4.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:211
  def anonymous_registry(&block); end

  # @since 0.6.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:154
  def build_command(command); end

  # Check if command
  #
  # @param command [Object] the command to check
  #
  # @return [TrueClass,FalseClass] true if instance of `Dry::CLI::Command`
  #
  # @since 0.1.0
  # @api private
  #
  # @see .command?
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:199
  def command?(command); end

  # @since 0.6.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:89
  def err; end

  # @since 0.6.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:167
  def error(result); end

  # @since 0.6.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:160
  def help(command, prog_name); end

  # @since 0.6.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:81
  def kommand; end

  # @since 0.6.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:85
  def out; end

  # Parse arguments for a command.
  #
  # It may exit in case of error, or in case of help.
  #
  # @param result [Dry::CLI::CommandRegistry::LookupResult]
  # @param out [IO] sta output
  #
  # @return [Array<Dry:CLI::Command, Array>] returns an array where the
  #   first element is a command and the second one is the list of arguments
  #
  # @since 0.6.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:140
  def parse(command, arguments, names); end

  # Invoke the CLI if singular command passed
  #
  # @param arguments [Array<string>] the command line arguments
  # @param out [IO] the standard output (defaults to `$stdout`)
  #
  # @since 0.6.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:98
  def perform_command(arguments); end

  # Invoke the CLI if registry passed
  #
  # @param arguments [Array<string>] the command line arguments
  # @param out [IO] the standard output (defaults to `$stdout`)
  #
  # @since 0.6.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:114
  def perform_registry(arguments); end

  # @since 0.6.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:77
  def registry; end

  # Handles Exit codes for signals
  # Fatal error signal "n". Say 130 = 128 + 2 (SIGINT) or 137 = 128 + 9 (SIGKILL)
  #
  # @since 0.7.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:185
  def signal_exception(exception); end

  # @since 1.1.1
  #
  # pkg:gem/dry-cli#lib/dry/cli.rb:173
  def spell_checker(result, arguments); end

  class << self
    # Check if command
    #
    # @param command [Object] the command to check
    #
    # @return [TrueClass,FalseClass] true if instance of `Dry::CLI::Command`
    #
    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli.rb:29
    def command?(command); end
  end
end

# Command line argument
#
# @since 0.1.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/option.rb:142
class Dry::CLI::Argument < ::Dry::CLI::Option
  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:145
  def argument?; end
end

# Command banner
#
# @since 0.1.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/banner.rb:11
module Dry::CLI::Banner
  class << self
    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:85
    def arguments(command); end

    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:130
    def build_subcommands_list(subcommands); end

    # Prints command banner
    #
    # @param command [Dry::CLI::Command] the command
    # @param out [IO] standard output
    #
    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:19
    def call(command, name); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:71
    def command_arguments(command); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:57
    def command_description(command); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:49
    def command_examples(command, name); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:33
    def command_name(name); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:39
    def command_name_and_arguments(command, name); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:79
    def command_options(command); end

    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:63
    def command_subcommands(command); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:98
    def extended_command_arguments(command); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:107
    def extended_command_options(command); end
  end
end

# Base class for commands
#
# @since 0.1.0
#
# pkg:gem/dry-cli#lib/dry/cli/command.rb:11
class Dry::CLI::Command
  extend ::Forwardable

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def arguments(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def default_params(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def description(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def examples(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def optional_arguments(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def options(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def params(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def required_arguments(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def subcommands(*_arg0, **_arg1, &_arg2); end

  protected

  # The error output used to print error messaging
  #
  # @example
  #   class MyCommand
  #     def call
  #       out.puts "Hello World!"
  #       exit(0)
  #     rescue StandardError => e
  #       err.puts "Uh oh: #{e.message}"
  #       exit(1)
  #     end
  #   end
  #
  # @since unreleased
  # @return [IO]
  #
  # pkg:gem/dry-cli#lib/dry/cli/command.rb:410
  def err; end

  # The standard output object used to print messaging
  #
  # @example
  #   class MyCommand
  #     def call
  #       out.puts "Hello World!"
  #       exit(0)
  #     end
  #   end
  #
  # @since unreleased
  # @return [IO]
  #
  # pkg:gem/dry-cli#lib/dry/cli/command.rb:424
  def out; end

  class << self
    # Specify an argument
    #
    # @param name [Symbol] the argument name
    # @param options [Hash] a set of options
    #
    # @since 0.1.0
    #
    # @example Optional argument
    #   require "dry/cli"
    #
    #   class Hello < Dry::CLI::Command
    #     argument :name
    #
    #     def call(name: nil, **)
    #       if name.nil?
    #         puts "Hello, stranger"
    #       else
    #         puts "Hello, #{name}"
    #       end
    #     end
    #   end
    #
    #   # $ foo hello
    #   #   Hello, stranger
    #
    #   # $ foo hello Luca
    #   #   Hello, Luca
    #
    # @example Required argument
    #   require "dry/cli"
    #
    #   class Hello < Dry::CLI::Command
    #     argument :name, required: true
    #
    #     def call(name:, **)
    #       puts "Hello, #{name}"
    #     end
    #   end
    #
    #   # $ foo hello Luca
    #   #   Hello, Luca
    #
    #   # $ foo hello
    #   #   ERROR: "foo hello" was called with no arguments
    #   #   Usage: "foo hello NAME"
    #
    # @example Multiple arguments
    #   require "dry/cli"
    #
    #   module Generate
    #     class Action < Dry::CLI::Command
    #       argument :app,    required: true
    #       argument :action, required: true
    #
    #       def call(app:, action:, **)
    #         puts "Generating action: #{action} for app: #{app}"
    #       end
    #     end
    #   end
    #
    #   # $ foo generate action web home
    #   #   Generating action: home for app: web
    #
    #   # $ foo generate action
    #   #   ERROR: "foo generate action" was called with no arguments
    #   #   Usage: "foo generate action APP ACTION"
    #
    # @example Description
    #   require "dry/cli"
    #
    #   class Hello < Dry::CLI::Command
    #     argument :name, desc: "The name of the person to greet"
    #
    #     def call(name: nil, **)
    #       # ...
    #     end
    #   end
    #
    #   # $ foo hello --help
    #   #   Command:
    #   #     foo hello
    #   #
    #   #   Usage:
    #   #     foo hello [NAME]
    #   #
    #   #   Arguments:
    #   #     NAME                # The name of the person to greet
    #   #
    #   #   Options:
    #   #     --help, -h          # Print this help
    #
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:197
    def argument(name, options = T.unsafe(nil)); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:335
    def default_params; end

    # Set the description of the command
    #
    # @param description [String] the description
    #
    # @since 0.1.0
    #
    # @example
    #   require "dry/cli"
    #
    #   class Echo < Dry::CLI::Command
    #     desc "Prints given input"
    #
    #     def call(*)
    #       # ...
    #     end
    #   end
    #
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:67
    def desc(description); end

    # Describe the usage of the command
    #
    # @param examples [Array<String>] one or more examples
    #
    # @since 0.1.0
    #
    # @example
    #   require "dry/cli"
    #
    #   class Server < Dry::CLI::Command
    #     example [
    #       "                    # Basic usage (it uses the bundled server engine)",
    #       "--server=webrick    # Force `webrick` server engine",
    #       "--host=0.0.0.0      # Bind to a host",
    #       "--port=2306         # Bind to a port",
    #       "--no-code-reloading # Disable code reloading"
    #     ]
    #
    #     def call(*)
    #       # ...
    #     end
    #   end
    #
    #   # $ foo server --help
    #   #   # ...
    #   #
    #   #   Examples:
    #   #     foo server                     # Basic usage (it uses the bundled server engine)
    #   #     foo server --server=webrick    # Force `webrick` server engine
    #   #     foo server --host=0.0.0.0      # Bind to a host
    #   #     foo server --port=2306         # Bind to a port
    #   #     foo server --no-code-reloading # Disable code reloading
    #
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:103
    def example(*examples); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:14
    def inherited(base); end

    # Command line option (aka optional argument)
    #
    # @param name [Symbol] the param name
    # @param options [Hash] a set of options
    #
    # @since 0.1.0
    #
    # @example Basic usage
    #   require "dry/cli"
    #
    #   class Console < Dry::CLI::Command
    #     option :engine
    #
    #     def call(engine: nil, **)
    #       puts "starting console (engine: #{engine || :irb})"
    #     end
    #   end
    #
    #   # $ foo console
    #   # starting console (engine: irb)
    #
    #   # $ foo console --engine=pry
    #   # starting console (engine: pry)
    #
    # @example List values
    #   require "dry/cli"
    #
    #   class Console < Dry::CLI::Command
    #     option :engine, values: %w(irb pry ripl)
    #
    #     def call(engine: nil, **)
    #       puts "starting console (engine: #{engine || :irb})"
    #     end
    #   end
    #
    #   # $ foo console
    #   # starting console (engine: irb)
    #
    #   # $ foo console --engine=pry
    #   # starting console (engine: pry)
    #
    #   # $ foo console --engine=foo
    #   # ERROR: Invalid param provided
    #
    # @example Description
    #   require "dry/cli"
    #
    #   class Console < Dry::CLI::Command
    #     option :engine, desc: "Force a console engine"
    #
    #     def call(engine: nil, **)
    #       # ...
    #     end
    #   end
    #
    #   # $ foo console --help
    #   # # ...
    #   #
    #   # Options:
    #   #   --engine=VALUE                  # Force a console engine: (irb/pry/ripl)
    #   #   --help, -h                      # Print this help
    #
    # @example Boolean
    #   require "dry/cli"
    #
    #   class Server < Dry::CLI::Command
    #     option :code_reloading, type: :boolean, default: true
    #
    #     def call(code_reloading:, **)
    #       puts "staring server (code reloading: #{code_reloading})"
    #     end
    #   end
    #
    #   # $ foo server
    #   # starting server (code reloading: true)
    #
    #   # $ foo server --no-code-reloading
    #   # starting server (code reloading: false)
    #
    #   # $ foo server --help
    #   # # ...
    #   #
    #   # Options:
    #   #   --[no]-code-reloading
    #
    # @example Aliases
    #   require "dry/cli"
    #
    #   class Server < Dry::CLI::Command
    #     option :port, aliases: ["-p"]
    #
    #     def call(options)
    #       puts "staring server (port: #{options.fetch(:port, 2300)})"
    #     end
    #   end
    #
    #   # $ foo server
    #   # starting server (port: 2300)
    #
    #   # $ foo server --port=2306
    #   # starting server (port: 2306)
    #
    #   # $ foo server -p 2306
    #   # starting server (port: 2306)
    #
    #   # $ foo server --help
    #   # # ...
    #   #
    #   # Options:
    #   #   --port=VALUE, -p VALUE
    #
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:316
    def option(name, options = T.unsafe(nil)); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:349
    def optional_arguments; end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:327
    def params; end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:343
    def required_arguments; end

    # @since 0.7.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:355
    def subcommands; end

    # @since 0.7.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:369
    def superclass_arguments; end

    # @since 0.7.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:375
    def superclass_options; end

    # @since 0.7.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:361
    def superclass_variable_dup(var); end
  end
end

# @since 0.1.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/command.rb:29
module Dry::CLI::Command::ClassMethods
  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command.rb:40
  def arguments; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command.rb:32
  def description; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command.rb:36
  def examples; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command.rb:44
  def options; end

  # @since 0.7.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command.rb:48
  def subcommands; end

  # @since 0.7.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command.rb:48
  def subcommands=(_arg0); end
end

# Command registry
#
# @since 0.1.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:9
class Dry::CLI::CommandRegistry
  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:12
  def initialize; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:40
  def get(arguments); end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:19
  def set(name, command, aliases, hidden); end
end

# Callbacks chain
#
# @since 0.4.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:237
class Dry::CLI::CommandRegistry::Chain
  # @since 0.4.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:244
  def initialize; end

  # @since 0.4.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:250
  def append(&callback); end

  # @since 0.4.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:240
  def chain; end

  # @since 0.4.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:256
  def run(context, **args); end
end

# Result of a registry lookup
#
# @since 0.1.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:184
class Dry::CLI::CommandRegistry::LookupResult
  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:195
  def initialize(node, arguments, names, found); end

  # @since 0.2.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:228
  def after_callbacks; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:191
  def arguments; end

  # @since 0.2.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:222
  def before_callbacks; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:210
  def children; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:216
  def command; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:204
  def found?; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:187
  def names; end
end

# Node of the registry
#
# @since 0.1.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:80
class Dry::CLI::CommandRegistry::Node
  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:111
  def initialize(parent = T.unsafe(nil)); end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:107
  def after_callbacks; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:149
  def alias!(key, child); end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:91
  def aliases; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:155
  def aliases!(aliases); end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:103
  def before_callbacks; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:87
  def children; end

  # @since 0.7.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:175
  def children?; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:99
  def command; end

  # @since 1.1.1
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:95
  def hidden; end

  # @since 1.1.1
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:163
  def hidden!(hidden); end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:136
  def leaf!(command); end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:169
  def leaf?; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:130
  def lookup(token); end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:83
  def parent; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:124
  def put(parent, key); end

  # @since 0.7.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:142
  def subcommands!(command); end
end

# @since 0.2.0
#
# pkg:gem/dry-cli#lib/dry/cli/errors.rb:9
class Dry::CLI::Error < ::StandardError; end

# @api private
# @since 0.5.0
#
# pkg:gem/dry-cli#lib/dry/cli/inflector.rb:7
module Dry::CLI::Inflector
  class << self
    # @api private
    # @since 0.5.0
    #
    # pkg:gem/dry-cli#lib/dry/cli/inflector.rb:10
    def dasherize(input); end
  end
end

# @since 0.2.0
#
# pkg:gem/dry-cli#lib/dry/cli/errors.rb:26
class Dry::CLI::InvalidCallbackError < ::Dry::CLI::Error
  # @since 0.2.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/errors.rb:29
  def initialize(callback); end
end

# Command line option
#
# @since 0.1.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/option.rb:9
class Dry::CLI::Option
  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:20
  def initialize(name, options = T.unsafe(nil)); end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:116
  def alias_names; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:27
  def aliases; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:87
  def argument?; end

  # @since 0.3.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:69
  def array?; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:58
  def boolean?; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:75
  def default; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:33
  def desc; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:81
  def description_name; end

  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:63
  def flag?; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:12
  def name; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:16
  def options; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:94
  def parser_options; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:40
  def required?; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:46
  def type; end

  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:126
  def valid_value?(value); end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:52
  def values; end
end

# Parse command line arguments and options
#
# @since 0.1.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/parser.rb:12
module Dry::CLI::Parser
  class << self
    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/parser.rb:16
    def call(command, arguments, prog_name); end

    # pkg:gem/dry-cli#lib/dry/cli/parser.rb:72
    def match_arguments(command_arguments, arguments, default_values); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/parser.rb:42
    def parse_required_params(command, arguments, prog_name, parsed_options); end
  end
end

# @since 0.1.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/parser.rb:96
class Dry::CLI::Parser::Result
  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/parser.rb:125
  def initialize(arguments: T.unsafe(nil), error: T.unsafe(nil), help: T.unsafe(nil)); end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/parser.rb:117
  def arguments; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/parser.rb:121
  def error; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/parser.rb:133
  def error?; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/parser.rb:139
  def help?; end

  class << self
    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/parser.rb:111
    def failure(error = T.unsafe(nil)); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/parser.rb:99
    def help; end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/parser.rb:105
    def success(arguments = T.unsafe(nil)); end
  end
end

# Program name
#
# @since 0.1.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/program_name.rb:9
module Dry::CLI::ProgramName
  class << self
    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/program_name.rb:16
    def call(names = T.unsafe(nil), program_name: T.unsafe(nil)); end
  end
end

# @since 0.1.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/program_name.rb:12
Dry::CLI::ProgramName::SEPARATOR = T.let(T.unsafe(nil), String)

# Registry mixin
#
# @since 0.1.0
#
# pkg:gem/dry-cli#lib/dry/cli/registry.rb:10
module Dry::CLI::Registry
  # Register an after callback.
  #
  # @param command_name [String] the name used for command registration
  # @param callback [Class, #call] the callback object. If a class is given,
  #   it MUST respond to `#call`.
  # @param blk [Proc] the callback espressed as a block
  #
  # @raise [Dry::CLI::UnknownCommandError] if the command isn't registered
  # @raise [Dry::CLI::InvalidCallbackError] if the given callback doesn't
  #   implement the required interface
  #
  # @since 0.2.0
  #
  # @example
  #   require "dry/cli"
  #
  #   module Foo
  #     module Commands
  #       extend Dry::CLI::Registry
  #
  #       class Hello < Dry::CLI::Command
  #         def call(*)
  #           puts "hello"
  #         end
  #       end
  #
  #       register "hello", Hello
  #       after "hello", -> { puts "world" }
  #     end
  #   end
  #
  # @example Register an object as callback
  #   require "dry/cli"
  #
  #   module Callbacks
  #     class World
  #       def call(*)
  #         puts "world"
  #       end
  #     end
  #   end
  #
  #   module Foo
  #     module Commands
  #       extend Dry::CLI::Registry
  #
  #       class Hello < Dry::CLI::Command
  #         def call(*)
  #           puts "hello"
  #         end
  #       end
  #
  #       register "hello", Hello
  #       after "hello", Callbacks::World.new
  #     end
  #   end
  #
  # @example Register a class as callback
  #   require "dry/cli"
  #
  #   module Callbacks
  #     class World
  #       def call(*)
  #         puts "world"
  #       end
  #     end
  #   end
  #
  #   module Foo
  #     module Commands
  #       extend Dry::CLI::Registry
  #
  #       class Hello < Dry::CLI::Command
  #         def call(*)
  #           puts "hello"
  #         end
  #       end
  #
  #       register "hello", Hello
  #       after "hello", Callbacks::World
  #     end
  #   end
  #
  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:261
  def after(command_name, callback = T.unsafe(nil), &blk); end

  # Register a before callback.
  #
  # @param command_name [String] the name used for command registration
  # @param callback [Class, #call] the callback object. If a class is given,
  #   it MUST respond to `#call`.
  # @param blk [Proc] the callback espressed as a block
  #
  # @raise [Dry::CLI::UnknownCommandError] if the command isn't registered
  # @raise [Dry::CLI::InvalidCallbackError] if the given callback doesn't
  #   implement the required interface
  #
  # @since 0.2.0
  #
  # @example
  #   require "dry/cli"
  #
  #   module Foo
  #     module Commands
  #       extend Dry::CLI::Registry
  #
  #       class Hello < Dry::CLI::Command
  #         def call(*)
  #           puts "hello"
  #         end
  #       end
  #
  #       register "hello", Hello
  #       before "hello", -> { puts "I'm about to say.." }
  #     end
  #   end
  #
  # @example Register an object as callback
  #   require "dry/cli"
  #
  #   module Callbacks
  #     class Hello
  #       def call(*)
  #         puts "world"
  #       end
  #     end
  #   end
  #
  #   module Foo
  #     module Commands
  #       extend Dry::CLI::Registry
  #
  #       class Hello < Dry::CLI::Command
  #         def call(*)
  #           puts "I'm about to say.."
  #         end
  #       end
  #
  #       register "hello", Hello
  #       before "hello", Callbacks::Hello.new
  #     end
  #   end
  #
  # @example Register a class as callback
  #   require "dry/cli"
  #
  #   module Callbacks
  #     class Hello
  #       def call(*)
  #         puts "world"
  #       end
  #     end
  #   end
  #
  #   module Foo
  #     module Commands
  #       extend Dry::CLI::Registry
  #
  #       class Hello < Dry::CLI::Command
  #         def call(*)
  #           puts "I'm about to say.."
  #         end
  #       end
  #
  #       register "hello", Hello
  #       before "hello", Callbacks::Hello
  #     end
  #   end
  #
  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:173
  def before(command_name, callback = T.unsafe(nil), &blk); end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:269
  def get(arguments); end

  # Register a command
  #
  # @param name [String] the command name
  # @param command [NilClass,Dry::CLI::Command] the optional command
  # @param aliases [Array<String>] an optional list of aliases
  # @param options [Hash] a set of options
  #
  # @since 0.1.0
  #
  # @example Register a command
  #   require "dry/cli"
  #
  #   module Foo
  #     module Commands
  #       extend Dry::CLI::Registry
  #
  #       class Hello < Dry::CLI::Command
  #       end
  #
  #       register "hi", Hello
  #     end
  #   end
  #
  # @example Register a command with aliases
  #   require "dry/cli"
  #
  #   module Foo
  #     module Commands
  #       extend Dry::CLI::Registry
  #
  #       class Hello < Dry::CLI::Command
  #       end
  #
  #       register "hello", Hello, aliases: ["hi", "ciao"]
  #     end
  #   end
  #
  # @example Register a group of commands
  #   require "dry/cli"
  #
  #   module Foo
  #     module Commands
  #       extend Dry::CLI::Registry
  #
  #       module Generate
  #         class App < Dry::CLI::Command
  #         end
  #
  #         class Action < Dry::CLI::Command
  #         end
  #       end
  #
  #       register "generate", aliases: ["g"] do |prefix|
  #         prefix.register "app",    Generate::App
  #         prefix.register "action", Generate::Action
  #       end
  #     end
  #   end
  #
  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:78
  def register(name, command = T.unsafe(nil), aliases: T.unsafe(nil), hidden: T.unsafe(nil), &block); end

  private

  # @since 0.2.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:288
  def _callback(callback, blk); end

  # @since 0.2.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:279
  def command(command_name); end

  class << self
    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/registry.rb:13
    def extended(base); end
  end
end

# pkg:gem/dry-cli#lib/dry/cli/registry.rb:275
Dry::CLI::Registry::COMMAND_NAME_SEPARATOR = T.let(T.unsafe(nil), String)

# Command name prefix
#
# @since 0.1.0
#
# pkg:gem/dry-cli#lib/dry/cli/registry.rb:308
class Dry::CLI::Registry::Prefix
  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:311
  def initialize(registry, prefix, aliases, hidden); end

  # @since 0.1.0
  #
  # @see Dry::CLI::Registry#register
  #
  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:321
  def register(name, command = T.unsafe(nil), aliases: T.unsafe(nil), hidden: T.unsafe(nil), &block); end

  private

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:343
  def prefix; end

  # @since 0.1.0
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:339
  def registry; end
end

# Command(s) usage
#
# @since 1.1.1
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/spell_checker.rb:12
module Dry::CLI::SpellChecker
  class << self
    # @since 1.1.1
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/spell_checker.rb:15
    def call(result, arguments); end

    # @since 1.1.1
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/spell_checker.rb:27
    def cmd_to_spell(arguments, result_names); end

    # @since 1.1.1
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/spell_checker.rb:33
    def ignore?(cmd); end
  end
end

# @since 0.2.1
#
# pkg:gem/dry-cli#lib/dry/cli/errors.rb:17
class Dry::CLI::UnknownCommandError < ::Dry::CLI::Error
  # @since 0.2.1
  # @api private
  #
  # pkg:gem/dry-cli#lib/dry/cli/errors.rb:20
  def initialize(command_name); end
end

# Command(s) usage
#
# @since 0.1.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/usage.rb:11
module Dry::CLI::Usage
  class << self
    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:54
    def arguments(command); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:19
    def call(result); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:91
    def command_name(result, name); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:85
    def commands(result); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:33
    def commands_and_arguments(result); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:69
    def description(command); end

    # @since 0.1.0
    # @api private
    #
    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:77
    def justify(string, padding, usage); end
  end
end

# pkg:gem/dry-cli#lib/dry/cli/usage.rb:15
Dry::CLI::Usage::ROOT_COMMAND_WITH_SUBCOMMANDS_BANNER = T.let(T.unsafe(nil), String)

# @since 0.1.0
# @api private
#
# pkg:gem/dry-cli#lib/dry/cli/usage.rb:14
Dry::CLI::Usage::SUBCOMMAND_BANNER = T.let(T.unsafe(nil), String)

# @since 0.1.0
#
# pkg:gem/dry-cli#lib/dry/cli/version.rb:6
Dry::CLI::VERSION = T.let(T.unsafe(nil), String)

# @since 1.4.0
#
# pkg:gem/dry-cli#lib/dry/cli/errors.rb:13
class Dry::CLI::ValueError < ::Dry::CLI::Error; end
