# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `graphlient` gem.
# Please instead update this file by running `bin/tapioca gem graphlient`.


# pkg:gem/graphlient#lib/graphlient/version.rb:1
module Graphlient; end

# pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:2
module Graphlient::Adapters; end

# pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:3
module Graphlient::Adapters::HTTP; end

# pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:4
class Graphlient::Adapters::HTTP::Adapter
  # @return [Adapter] a new instance of Adapter
  # @yield [_self]
  # @yieldparam _self [Graphlient::Adapters::HTTP::Adapter] the object that the method was called on
  #
  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:7
  def initialize(url, options = T.unsafe(nil), &_block); end

  # @raise [NotImplementedError]
  #
  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:23
  def execute(*_arg0); end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:13
  def headers; end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:17
  def http_options; end

  # Returns the value of attribute options.
  #
  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:5
  def options; end

  # Sets the attribute options
  #
  # @param value the value to set the attribute options to.
  #
  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:5
  def options=(_arg0); end

  # Returns the value of attribute url.
  #
  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:5
  def url; end

  # Sets the attribute url
  #
  # @param value the value to set the attribute url to.
  #
  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:5
  def url=(_arg0); end

  private

  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:29
  def configure_http_options(client_options); end
end

# pkg:gem/graphlient#lib/graphlient/adapters/http/faraday_adapter.rb:7
class Graphlient::Adapters::HTTP::FaradayAdapter < ::Graphlient::Adapters::HTTP::Adapter
  # pkg:gem/graphlient#lib/graphlient/adapters/http/faraday_adapter.rb:29
  def connection; end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/faraday_adapter.rb:8
  def execute(document:, operation_name:, variables:, context:); end

  private

  # Faraday 2.x's JSON response middleware will only parse a JSON
  # response body into a Hash (or Array) object if the response headers
  # match a specific content type regex. See Faraday's response JSON
  # middleware definition for specifics on what the datatype of the
  # response body will be. This method will handle the situation where
  # the response header is not set appropriately, but contains JSON
  # anyways. If the body cannot be parsed as JSON, an exception will be
  # raised.
  #
  # pkg:gem/graphlient#lib/graphlient/adapters/http/faraday_adapter.rb:55
  def parse_body(body); end
end

# pkg:gem/graphlient#lib/graphlient/adapters/http/http_adapter.rb:6
class Graphlient::Adapters::HTTP::HTTPAdapter < ::Graphlient::Adapters::HTTP::Adapter
  # pkg:gem/graphlient#lib/graphlient/adapters/http/http_adapter.rb:29
  def connection; end

  # @raise [Graphlient::Errors::HttpServerError]
  #
  # pkg:gem/graphlient#lib/graphlient/adapters/http/http_adapter.rb:7
  def execute(document:, operation_name: T.unsafe(nil), variables: T.unsafe(nil), context: T.unsafe(nil)); end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/http_adapter.rb:25
  def uri; end
end

# pkg:gem/graphlient#lib/graphlient/client.rb:2
class Graphlient::Client
  # @return [Client] a new instance of Client
  # @yield [_self]
  # @yieldparam _self [Graphlient::Client] the object that the method was called on
  #
  # pkg:gem/graphlient#lib/graphlient/client.rb:7
  def initialize(url, options = T.unsafe(nil), &_block); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:23
  def execute(query, variables = T.unsafe(nil)); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:50
  def http(&block); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:46
  def http_adapter_class; end

  # Returns the value of attribute options.
  #
  # pkg:gem/graphlient#lib/graphlient/client.rb:3
  def options; end

  # Sets the attribute options
  #
  # @param value the value to set the attribute options to.
  #
  # pkg:gem/graphlient#lib/graphlient/client.rb:3
  def options=(_arg0); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:14
  def parse(query_str = T.unsafe(nil), &block); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:38
  def query(query_or_variables = T.unsafe(nil), variables = T.unsafe(nil), &block); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:56
  def schema; end

  # Returns the value of attribute uri.
  #
  # pkg:gem/graphlient#lib/graphlient/client.rb:3
  def uri; end

  # Sets the attribute uri
  #
  # @param value the value to set the attribute uri to.
  #
  # pkg:gem/graphlient#lib/graphlient/client.rb:3
  def uri=(_arg0); end

  private

  # pkg:gem/graphlient#lib/graphlient/client.rb:70
  def client; end

  # @return [Boolean]
  #
  # pkg:gem/graphlient#lib/graphlient/client.rb:76
  def errors_in_result?(response); end

  # @raise [InvalidConfigurationError]
  #
  # pkg:gem/graphlient#lib/graphlient/client.rb:62
  def raise_error_if_invalid_configuration!; end

  # pkg:gem/graphlient#lib/graphlient/client.rb:66
  def schema_path; end
end

# pkg:gem/graphlient#lib/graphlient/client.rb:5
class Graphlient::Client::InvalidConfigurationError < ::StandardError; end

# pkg:gem/graphlient#lib/graphlient/errors/error.rb:2
module Graphlient::Errors; end

# pkg:gem/graphlient#lib/graphlient/errors/client_error.rb:3
class Graphlient::Errors::ClientError < ::Graphlient::Errors::Error; end

# pkg:gem/graphlient#lib/graphlient/errors/connection_failed_error.rb:3
class Graphlient::Errors::ConnectionFailedError < ::Graphlient::Errors::ServerError; end

# pkg:gem/graphlient#lib/graphlient/errors/error.rb:3
class Graphlient::Errors::Error < ::StandardError
  # @return [Error] a new instance of Error
  #
  # pkg:gem/graphlient#lib/graphlient/errors/error.rb:5
  def initialize(message, inner_exception = T.unsafe(nil)); end

  # Returns the value of attribute inner_exception.
  #
  # pkg:gem/graphlient#lib/graphlient/errors/error.rb:4
  def inner_exception; end
end

# pkg:gem/graphlient#lib/graphlient/errors/execution_error.rb:3
class Graphlient::Errors::ExecutionError < ::Graphlient::Errors::Error
  # @return [ExecutionError] a new instance of ExecutionError
  #
  # pkg:gem/graphlient#lib/graphlient/errors/execution_error.rb:6
  def initialize(response); end

  # pkg:gem/graphlient#lib/graphlient/errors/execution_error.rb:11
  def errors; end

  # Returns the value of attribute response.
  #
  # pkg:gem/graphlient#lib/graphlient/errors/execution_error.rb:4
  def response; end

  # pkg:gem/graphlient#lib/graphlient/errors/execution_error.rb:15
  def to_s; end

  private

  # pkg:gem/graphlient#lib/graphlient/errors/execution_error.rb:24
  def create_details(details); end
end

# pkg:gem/graphlient#lib/graphlient/errors/faraday_server_error.rb:3
class Graphlient::Errors::FaradayServerError < ::Graphlient::Errors::ServerError
  # @return [FaradayServerError] a new instance of FaradayServerError
  #
  # pkg:gem/graphlient#lib/graphlient/errors/faraday_server_error.rb:4
  def initialize(inner_exception); end
end

# pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:3
class Graphlient::Errors::GraphQLError < ::Graphlient::Errors::Error
  # @return [GraphQLError] a new instance of GraphQLError
  #
  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:5
  def initialize(response); end

  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:10
  def errors; end

  # Returns the value of attribute response.
  #
  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:4
  def response; end

  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:14
  def to_s; end

  private

  # Generates human readable error explanation from a GraphQL error message
  # It first tries `problem` attribute of the error response
  # then checks for error root level `path` and tries to generate error from that
  # and if none exist, it fallbacks to just return error message
  #
  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:32
  def create_detail(detail); end

  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:23
  def create_details(details); end

  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:46
  def create_problem(problem); end

  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:42
  def create_problems(problems); end
end

# pkg:gem/graphlient#lib/graphlient/errors/http_options_error.rb:3
class Graphlient::Errors::HttpOptionsError < ::Graphlient::Errors::Error; end

# pkg:gem/graphlient#lib/graphlient/errors/http_server_error.rb:3
class Graphlient::Errors::HttpServerError < ::Graphlient::Errors::Error
  # @return [HttpServerError] a new instance of HttpServerError
  #
  # pkg:gem/graphlient#lib/graphlient/errors/http_server_error.rb:6
  def initialize(message, response); end

  # Returns the value of attribute response.
  #
  # pkg:gem/graphlient#lib/graphlient/errors/http_server_error.rb:4
  def response; end

  # Returns the value of attribute status_code.
  #
  # pkg:gem/graphlient#lib/graphlient/errors/http_server_error.rb:4
  def status_code; end
end

# pkg:gem/graphlient#lib/graphlient/errors/server_error.rb:3
class Graphlient::Errors::ServerError < ::Graphlient::Errors::Error
  # Returns the value of attribute response.
  #
  # pkg:gem/graphlient#lib/graphlient/errors/server_error.rb:4
  def response; end

  # Returns the value of attribute status_code.
  #
  # pkg:gem/graphlient#lib/graphlient/errors/server_error.rb:4
  def status_code; end
end

# pkg:gem/graphlient#lib/graphlient/errors/timeout_error.rb:3
class Graphlient::Errors::TimeoutError < ::Graphlient::Errors::Error; end

# pkg:gem/graphlient#lib/graphlient/extensions/query.rb:2
module Graphlient::Extensions; end

# pkg:gem/graphlient#lib/graphlient/extensions/query.rb:3
module Graphlient::Extensions::Query
  # pkg:gem/graphlient#lib/graphlient/extensions/query.rb:4
  def method_missing(method_name, *args, &block); end

  private

  # @return [Boolean]
  #
  # pkg:gem/graphlient#lib/graphlient/extensions/query.rb:10
  def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end
end

# pkg:gem/graphlient#lib/graphlient/query.rb:2
class Graphlient::Query
  # @return [Query] a new instance of Query
  #
  # pkg:gem/graphlient#lib/graphlient/query.rb:16
  def initialize(&block); end

  # pkg:gem/graphlient#lib/graphlient/query.rb:23
  def method_missing(method_name, *args, &block); end

  # pkg:gem/graphlient#lib/graphlient/query.rb:28
  def mutation(*args, &block); end

  # pkg:gem/graphlient#lib/graphlient/query.rb:28
  def query(*args, &block); end

  # Returns the value of attribute query_str.
  #
  # pkg:gem/graphlient#lib/graphlient/query.rb:14
  def query_str; end

  # Sets the attribute query_str
  #
  # @param value the value to set the attribute query_str to.
  #
  # pkg:gem/graphlient#lib/graphlient/query.rb:14
  def query_str=(_arg0); end

  # pkg:gem/graphlient#lib/graphlient/query.rb:28
  def subscription(*args, &block); end

  # pkg:gem/graphlient#lib/graphlient/query.rb:38
  def to_s; end

  private

  # pkg:gem/graphlient#lib/graphlient/query.rb:59
  def append_node(node, args, arg_processor: T.unsafe(nil), &block); end

  # pkg:gem/graphlient#lib/graphlient/query.rb:87
  def args_str(hash_args, arg_processor: T.unsafe(nil)); end

  # pkg:gem/graphlient#lib/graphlient/query.rb:93
  def argument_string(key, val); end

  # pkg:gem/graphlient#lib/graphlient/query.rb:111
  def argument_value_string(value); end

  # pkg:gem/graphlient#lib/graphlient/query.rb:44
  def evaluate(&block); end

  # pkg:gem/graphlient#lib/graphlient/query.rb:83
  def hash_arg(args); end

  # pkg:gem/graphlient#lib/graphlient/query.rb:79
  def indent; end

  # pkg:gem/graphlient#lib/graphlient/query.rb:50
  def resolve_fragment_constant(value); end

  # @return [Boolean]
  #
  # pkg:gem/graphlient#lib/graphlient/query.rb:34
  def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end

  # pkg:gem/graphlient#lib/graphlient/query.rb:97
  def variable_string(val); end
end

# pkg:gem/graphlient#lib/graphlient/query.rb:12
Graphlient::Query::FRAGMENT_DEFITION = T.let(T.unsafe(nil), Regexp)

# pkg:gem/graphlient#lib/graphlient/query.rb:10
Graphlient::Query::ROOT_NODES = T.let(T.unsafe(nil), Array)

# pkg:gem/graphlient#lib/graphlient/query.rb:3
Graphlient::Query::SCALAR_TYPES = T.let(T.unsafe(nil), Hash)

# pkg:gem/graphlient#lib/graphlient/schema.rb:4
class Graphlient::Schema < ::SimpleDelegator
  # @return [Schema] a new instance of Schema
  #
  # pkg:gem/graphlient#lib/graphlient/schema.rb:13
  def initialize(http, path); end

  # @raise [MissingConfigurationError]
  #
  # pkg:gem/graphlient#lib/graphlient/schema.rb:21
  def dump!; end

  # pkg:gem/graphlient#lib/graphlient/schema.rb:9
  def graphql_schema; end

  # Returns the value of attribute http.
  #
  # pkg:gem/graphlient#lib/graphlient/schema.rb:11
  def http; end

  # Returns the value of attribute path.
  #
  # pkg:gem/graphlient#lib/graphlient/schema.rb:11
  def path; end
end

# pkg:gem/graphlient#lib/graphlient/schema.rb:7
class Graphlient::Schema::MissingConfigurationError < ::StandardError; end

# pkg:gem/graphlient#lib/graphlient/schema.rb:5
Graphlient::Schema::PATH_ERROR_MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/graphlient#lib/graphlient/version.rb:2
Graphlient::VERSION = T.let(T.unsafe(nil), String)
