# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `graphlient` gem.
# Please instead update this file by running `bin/tapioca gem graphlient`.


# pkg:gem/graphlient#lib/graphlient/version.rb:1
module Graphlient; end

# pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:2
module Graphlient::Adapters; end

# pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:3
module Graphlient::Adapters::HTTP; end

# pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:4
class Graphlient::Adapters::HTTP::Adapter
  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:7
  def initialize(url, options = T.unsafe(nil), &_block); end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:23
  def execute(*_arg0); end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:13
  def headers; end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:17
  def http_options; end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:5
  def options; end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:5
  def options=(_arg0); end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:5
  def url; end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:5
  def url=(_arg0); end

  private

  # pkg:gem/graphlient#lib/graphlient/adapters/http/adapter.rb:29
  def configure_http_options(client_options); end
end

# pkg:gem/graphlient#lib/graphlient/adapters/http/faraday_adapter.rb:7
class Graphlient::Adapters::HTTP::FaradayAdapter < ::Graphlient::Adapters::HTTP::Adapter
  # pkg:gem/graphlient#lib/graphlient/adapters/http/faraday_adapter.rb:29
  def connection; end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/faraday_adapter.rb:8
  def execute(document:, operation_name:, variables:, context:); end

  private

  # Faraday 2.x's JSON response middleware will only parse a JSON
  # response body into a Hash (or Array) object if the response headers
  # match a specific content type regex. See Faraday's response JSON
  # middleware definition for specifics on what the datatype of the
  # response body will be. This method will handle the situation where
  # the response header is not set appropriately, but contains JSON
  # anyways. If the body cannot be parsed as JSON, an exception will be
  # raised.
  #
  # pkg:gem/graphlient#lib/graphlient/adapters/http/faraday_adapter.rb:55
  def parse_body(body); end
end

# pkg:gem/graphlient#lib/graphlient/adapters/http/http_adapter.rb:6
class Graphlient::Adapters::HTTP::HTTPAdapter < ::Graphlient::Adapters::HTTP::Adapter
  # pkg:gem/graphlient#lib/graphlient/adapters/http/http_adapter.rb:30
  def connection; end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/http_adapter.rb:7
  def execute(document:, operation_name: T.unsafe(nil), variables: T.unsafe(nil), context: T.unsafe(nil)); end

  # pkg:gem/graphlient#lib/graphlient/adapters/http/http_adapter.rb:26
  def uri; end
end

# pkg:gem/graphlient#lib/graphlient/client.rb:2
class Graphlient::Client
  # pkg:gem/graphlient#lib/graphlient/client.rb:7
  def initialize(url, options = T.unsafe(nil), &_block); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:29
  def execute(query, variables = T.unsafe(nil)); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:57
  def http(&block); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:53
  def http_adapter_class; end

  # pkg:gem/graphlient#lib/graphlient/client.rb:3
  def options; end

  # pkg:gem/graphlient#lib/graphlient/client.rb:3
  def options=(_arg0); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:14
  def parse(query_str = T.unsafe(nil), &block); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:45
  def query(query_or_variables = T.unsafe(nil), variables = T.unsafe(nil), &block); end

  # Register a custom scalar type for use in variable declarations.
  # Call inside the client initialiser block:
  #   client = Graphlient::Client.new(url) do |c|
  #     c.scalar :date,    'Date'
  #     c.scalar :uuid,    'UUID'
  #     c.scalar :decimal, 'Decimal'
  #   end
  #
  # pkg:gem/graphlient#lib/graphlient/client.rb:70
  def scalar(sym, graphql_type); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:74
  def schema; end

  # pkg:gem/graphlient#lib/graphlient/client.rb:23
  def to_query_string(**_kargs, &block); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:3
  def uri; end

  # pkg:gem/graphlient#lib/graphlient/client.rb:3
  def uri=(_arg0); end

  private

  # pkg:gem/graphlient#lib/graphlient/client.rb:88
  def client; end

  # pkg:gem/graphlient#lib/graphlient/client.rb:94
  def errors_in_result?(response); end

  # pkg:gem/graphlient#lib/graphlient/client.rb:80
  def raise_error_if_invalid_configuration!; end

  # pkg:gem/graphlient#lib/graphlient/client.rb:84
  def schema_path; end
end

# pkg:gem/graphlient#lib/graphlient/client.rb:5
class Graphlient::Client::InvalidConfigurationError < ::StandardError; end

# pkg:gem/graphlient#lib/graphlient/errors/error.rb:2
module Graphlient::Errors; end

# pkg:gem/graphlient#lib/graphlient/errors/client_error.rb:3
class Graphlient::Errors::ClientError < ::Graphlient::Errors::Error; end

# pkg:gem/graphlient#lib/graphlient/errors/connection_failed_error.rb:3
class Graphlient::Errors::ConnectionFailedError < ::Graphlient::Errors::ServerError; end

# pkg:gem/graphlient#lib/graphlient/errors/error.rb:3
class Graphlient::Errors::Error < ::StandardError
  # pkg:gem/graphlient#lib/graphlient/errors/error.rb:6
  def initialize(message, inner_exception = T.unsafe(nil)); end

  # pkg:gem/graphlient#lib/graphlient/errors/error.rb:4
  def inner_exception; end
end

# pkg:gem/graphlient#lib/graphlient/errors/execution_error.rb:3
class Graphlient::Errors::ExecutionError < ::Graphlient::Errors::Error
  # pkg:gem/graphlient#lib/graphlient/errors/execution_error.rb:6
  def initialize(response); end

  # pkg:gem/graphlient#lib/graphlient/errors/execution_error.rb:11
  def errors; end

  # pkg:gem/graphlient#lib/graphlient/errors/execution_error.rb:4
  def response; end

  # pkg:gem/graphlient#lib/graphlient/errors/execution_error.rb:15
  def to_s; end

  private

  # pkg:gem/graphlient#lib/graphlient/errors/execution_error.rb:24
  def create_details(details); end
end

# pkg:gem/graphlient#lib/graphlient/errors/faraday_server_error.rb:3
class Graphlient::Errors::FaradayServerError < ::Graphlient::Errors::ServerError
  # pkg:gem/graphlient#lib/graphlient/errors/faraday_server_error.rb:4
  def initialize(inner_exception); end
end

# pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:3
class Graphlient::Errors::GraphQLError < ::Graphlient::Errors::Error
  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:6
  def initialize(response); end

  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:11
  def errors; end

  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:4
  def response; end

  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:15
  def to_s; end

  private

  # Generates human readable error explanation from a GraphQL error message
  # It first tries `problem` attribute of the error response
  # then checks for error root level `path` and tries to generate error from that
  # and if none exist, it fallbacks to just return error message
  #
  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:33
  def create_detail(detail); end

  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:24
  def create_details(details); end

  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:47
  def create_problem(problem); end

  # pkg:gem/graphlient#lib/graphlient/errors/graphql_error.rb:43
  def create_problems(problems); end
end

# pkg:gem/graphlient#lib/graphlient/errors/http_options_error.rb:3
class Graphlient::Errors::HttpOptionsError < ::Graphlient::Errors::Error; end

# pkg:gem/graphlient#lib/graphlient/errors/http_server_error.rb:3
class Graphlient::Errors::HttpServerError < ::Graphlient::Errors::Error
  # pkg:gem/graphlient#lib/graphlient/errors/http_server_error.rb:6
  def initialize(message, response); end

  # pkg:gem/graphlient#lib/graphlient/errors/http_server_error.rb:4
  def response; end

  # pkg:gem/graphlient#lib/graphlient/errors/http_server_error.rb:4
  def status_code; end
end

# pkg:gem/graphlient#lib/graphlient/errors/server_error.rb:3
class Graphlient::Errors::ServerError < ::Graphlient::Errors::Error
  # pkg:gem/graphlient#lib/graphlient/errors/server_error.rb:4
  def response; end

  # pkg:gem/graphlient#lib/graphlient/errors/server_error.rb:4
  def status_code; end
end

# pkg:gem/graphlient#lib/graphlient/errors/timeout_error.rb:3
class Graphlient::Errors::TimeoutError < ::Graphlient::Errors::Error; end

# pkg:gem/graphlient#lib/graphlient/extensions/query.rb:2
module Graphlient::Extensions; end

# pkg:gem/graphlient#lib/graphlient/extensions/query.rb:3
module Graphlient::Extensions::Query
  # pkg:gem/graphlient#lib/graphlient/extensions/query.rb:4
  def method_missing(method_name, *args, &block); end

  private

  # pkg:gem/graphlient#lib/graphlient/extensions/query.rb:10
  def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end
end

# Public interface for building GraphQL query strings via a DSL block.
# Delegates all string-building work to Query::Serializer.
#
# Usage:
#   Graphlient::Query.new do
#     query do
#       invoice(id: 10) { id; fee_in_cents }
#     end
#   end.to_s
#
# pkg:gem/graphlient#lib/graphlient/query/directive.rb:2
class Graphlient::Query
  # pkg:gem/graphlient#lib/graphlient/query.rb:21
  def initialize(&block); end

  # pkg:gem/graphlient#lib/graphlient/query.rb:25
  def to_s; end

  class << self
    # Register a custom scalar type for variable declarations.
    # Delegates to Serializer so client configuration works:
    #   client = Graphlient::Client.new(url) { |c| c.scalar :date, 'Date' }
    #
    # pkg:gem/graphlient#lib/graphlient/query.rb:17
    def scalar(sym, graphql_type); end
  end
end

# Value object returned by `_directive_name(args)` in the DSL.
#
# Rather than writing directly to the query string (which would produce
# the wrong position -- before the field name), _skip / _include etc.
# return a Directive instance.  append_node / spread / on detect Directive
# objects in their argument list and place them AFTER the field name,
# producing correct GraphQL output:
#
#   feeInCents _skip(if: :skip_fee)
#   -> feeInCents @skip(if: $skip_fee)
#
#   spread :InvoiceFields, _skip(if: :x)
#   -> ...InvoiceFields @skip(if: $x)
#
#   spread(_skip(if: :x), on: :DraftInvoice) { draft_id }
#   -> ... on DraftInvoice @skip(if: $x) { draftId }
#
# pkg:gem/graphlient#lib/graphlient/query/directive.rb:19
class Graphlient::Query::Directive
  # pkg:gem/graphlient#lib/graphlient/query/directive.rb:22
  def initialize(name, args = T.unsafe(nil)); end

  # pkg:gem/graphlient#lib/graphlient/query/directive.rb:20
  def args; end

  # pkg:gem/graphlient#lib/graphlient/query/directive.rb:20
  def name; end

  # pkg:gem/graphlient#lib/graphlient/query/directive.rb:27
  def to_s; end

  private

  # Symbols become variable references ($name); everything else is literal.
  #
  # pkg:gem/graphlient#lib/graphlient/query/directive.rb:37
  def format_value(value); end
end

# Builds a GraphQL query string from a DSL block.
# Composed from focused concern modules; Query is a thin public wrapper.
#
# pkg:gem/graphlient#lib/graphlient/query/serializer/scalars.rb:3
class Graphlient::Query::Serializer
  include ::Graphlient::Query::Serializer::Scalars
  include ::Graphlient::Query::Serializer::Arguments
  include ::Graphlient::Query::Serializer::Evaluator
  include ::Graphlient::Query::Serializer::Fragments
  include ::Graphlient::Query::Serializer::Directives
  extend ::Graphlient::Query::Serializer::Scalars::ClassMethods

  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:31
  def initialize(&block); end

  # Inline fragment definition -- collected and appended after the main query.
  #   fragment(:InvoiceFields, on: :Invoice) { id; fee_in_cents }
  #
  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:81
  def fragment(name, on:, &block); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:86
  def method_missing(method_name, *args, &block); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:23
  def mutation(*args, &block); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:23
  def query(*args, &block); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:29
  def query_str; end

  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:29
  def query_str=(_arg0); end

  # Fragment spread OR inline fragment -- one consistent entry point.
  #
  # Named fragment spread: ...FragmentName [@directive ...]
  #   spread :InvoiceFields
  #   spread :InvoiceFields, _skip(if: :x)          # -> ...InvoiceFields @skip(if: $x)
  #
  # Inline fragment / type condition: ... on Type [@directive ...] { fields }
  #   spread on: :PaidInvoice { amount_paid }       # -> ... on PaidInvoice { amountPaid }
  #   spread on: :DraftInvoice, _skip(if: :skip) { draft_id }
  #   spread on: :Invoice                           # bare type condition, no block
  #
  # A single verb covers both GraphQL forms; `on:` is the same keyword used by
  # `fragment(name, on:)`, keeping the DSL consistent (and leaving room for a future
  # `spread(:X).skip(...)` chaining form without a breaking change).
  #
  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:69
  def spread(*args, on: T.unsafe(nil), &block); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:23
  def subscription(*args, &block); end

  # Full output: main query string + any inline fragment definitions.
  #
  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:40
  def to_s; end

  private

  # Inline fragment / type condition: ... on Type [@directive ...] [{ fields }]
  #
  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:107
  def append_inline_fragment(type, directives, &block); end

  # Named fragment spread: ...FragmentName [@directive ...]
  #
  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:120
  def append_named_spread(args, directives, &block); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:129
  def append_node(node, args, arg_processor: T.unsafe(nil), &block); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:102
  def indent; end

  # pkg:gem/graphlient#lib/graphlient/query/serializer.rb:96
  def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end
end

# pkg:gem/graphlient#lib/graphlient/query/serializer/arguments.rb:4
module Graphlient::Query::Serializer::Arguments
  private

  # pkg:gem/graphlient#lib/graphlient/query/serializer/arguments.rb:39
  def args_str(hash_args, arg_processor: T.unsafe(nil)); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer/arguments.rb:45
  def argument_string(key, val); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer/arguments.rb:49
  def argument_value_string(value); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer/arguments.rb:31
  def directive_args(args); end

  # Separate Directive objects from regular field arguments.
  #
  # pkg:gem/graphlient#lib/graphlient/query/serializer/arguments.rb:27
  def field_args(args); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer/arguments.rb:35
  def hash_arg(args); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer/arguments.rb:61
  def symbol_argument_value(value); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer/arguments.rb:7
  def variable_processor; end

  # Translate a DSL variable type symbol to its GraphQL type string.
  # :id/:id! -> ID/ID!   :int -> Int   :date -> Date (if registered)   [:int] -> [Int]
  #
  # pkg:gem/graphlient#lib/graphlient/query/serializer/arguments.rb:13
  def variable_string(val); end
end

# pkg:gem/graphlient#lib/graphlient/query/serializer/directives.rb:4
module Graphlient::Query::Serializer::Directives
  private

  # pkg:gem/graphlient#lib/graphlient/query/serializer/directives.rb:11
  def directive?(method_name); end
end

# Matches _skip, _include, _myCustomDirective etc.
# Does NOT match ___Fragment (three underscores -- checked first in method_missing).
#
# pkg:gem/graphlient#lib/graphlient/query/serializer/directives.rb:7
Graphlient::Query::Serializer::Directives::DIRECTIVE_PREFIX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/graphlient#lib/graphlient/query/serializer/evaluator.rb:4
module Graphlient::Query::Serializer::Evaluator
  private

  # pkg:gem/graphlient#lib/graphlient/query/serializer/evaluator.rb:7
  def evaluate(&block); end
end

# pkg:gem/graphlient#lib/graphlient/query/serializer/fragments.rb:4
module Graphlient::Query::Serializer::Fragments
  private

  # pkg:gem/graphlient#lib/graphlient/query/serializer/fragments.rb:10
  def fragment?(method_name); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer/fragments.rb:14
  def resolve_fragment_constant(value); end
end

# Pattern for the legacy ___Const::Name triple-underscore convention.
#
# pkg:gem/graphlient#lib/graphlient/query/serializer/fragments.rb:6
Graphlient::Query::Serializer::Fragments::FRAGMENT_DEFINITION = T.let(T.unsafe(nil), Regexp)

# pkg:gem/graphlient#lib/graphlient/query/serializer.rb:20
Graphlient::Query::Serializer::ROOT_NODES = T.let(T.unsafe(nil), Array)

# Raised when a named spread is given a block (a named spread has no selection set).
#
# pkg:gem/graphlient#lib/graphlient/query/serializer.rb:51
Graphlient::Query::Serializer::SPREAD_NAME_TAKES_NO_BLOCK = T.let(T.unsafe(nil), String)

# Raised when `spread` is called with neither a fragment name nor `on:`.
#
# pkg:gem/graphlient#lib/graphlient/query/serializer.rb:47
Graphlient::Query::Serializer::SPREAD_REQUIRES_NAME_OR_ON = T.let(T.unsafe(nil), String)

# pkg:gem/graphlient#lib/graphlient/query/serializer/scalars.rb:4
module Graphlient::Query::Serializer::Scalars
  mixes_in_class_methods ::Graphlient::Query::Serializer::Scalars::ClassMethods

  private

  # pkg:gem/graphlient#lib/graphlient/query/serializer/scalars.rb:57
  def all_scalar_types; end

  # pkg:gem/graphlient#lib/graphlient/query/serializer/scalars.rb:45
  def scalar?(value); end

  # pkg:gem/graphlient#lib/graphlient/query/serializer/scalars.rb:49
  def scalar_type(value); end

  class << self
    # pkg:gem/graphlient#lib/graphlient/query/serializer/scalars.rb:12
    def included(base); end
  end
end

# pkg:gem/graphlient#lib/graphlient/query/serializer/scalars.rb:5
Graphlient::Query::Serializer::Scalars::BUILT_IN_SCALAR_TYPES = T.let(T.unsafe(nil), Hash)

# pkg:gem/graphlient#lib/graphlient/query/serializer/scalars.rb:16
module Graphlient::Query::Serializer::Scalars::ClassMethods
  # pkg:gem/graphlient#lib/graphlient/query/serializer/scalars.rb:38
  def all_scalar_types; end

  # pkg:gem/graphlient#lib/graphlient/query/serializer/scalars.rb:34
  def custom_scalar_types; end

  # Register a custom scalar type for use in variable declarations.
  #
  #   Graphlient::Query::Serializer.scalar(:date, 'Date')
  #
  # Typically called via the client configuration block:
  #   client = Graphlient::Client.new(url) do |c|
  #     c.scalar :date,    'Date'
  #     c.scalar :uuid,    'UUID'
  #     c.scalar :decimal, 'Decimal'
  #   end
  #
  # After registration, use the symbol in variable declarations:
  #   query(created_after: :date) { ... }  # -> query($createdAfter: Date)
  #
  # pkg:gem/graphlient#lib/graphlient/query/serializer/scalars.rb:30
  def scalar(sym, graphql_type); end
end

# pkg:gem/graphlient#lib/graphlient/schema.rb:4
class Graphlient::Schema < ::SimpleDelegator
  # pkg:gem/graphlient#lib/graphlient/schema.rb:13
  def initialize(http, path); end

  # pkg:gem/graphlient#lib/graphlient/schema.rb:21
  def dump!; end

  # pkg:gem/graphlient#lib/graphlient/schema.rb:9
  def graphql_schema; end

  # pkg:gem/graphlient#lib/graphlient/schema.rb:11
  def http; end

  # pkg:gem/graphlient#lib/graphlient/schema.rb:11
  def path; end
end

# pkg:gem/graphlient#lib/graphlient/schema.rb:7
class Graphlient::Schema::MissingConfigurationError < ::StandardError; end

# pkg:gem/graphlient#lib/graphlient/schema.rb:5
Graphlient::Schema::PATH_ERROR_MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/graphlient#lib/graphlient/version.rb:2
Graphlient::VERSION = T.let(T.unsafe(nil), String)
