# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `httplog` gem.
# Please instead update this file by running `bin/tapioca gem httplog`.


# pkg:gem/httplog#lib/httplog/version.rb:3
module HttpLog
  class << self
    # pkg:gem/httplog#lib/httplog/http_log.rb:32
    def call(options = T.unsafe(nil)); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:177
    def colorize(msg); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:21
    def config; end

    # pkg:gem/httplog#lib/httplog/http_log.rb:18
    def configuration; end

    # pkg:gem/httplog#lib/httplog/http_log.rb:16
    def configuration=(_arg0); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:27
    def configure; end

    # pkg:gem/httplog#lib/httplog/http_log.rb:61
    def log(msg); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:94
    def log_benchmark(seconds); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:100
    def log_body(body, mask_body, encoding = T.unsafe(nil), content_type = T.unsafe(nil)); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:167
    def log_compact(method, uri, status, seconds); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:67
    def log_connection(host, port = T.unsafe(nil)); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:156
    def log_data(data); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:79
    def log_headers(headers = T.unsafe(nil)); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:73
    def log_request(method, uri); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:87
    def log_status(status); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:57
    def masked_body_url?(url); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:115
    def parse_body(body, mask_body, encoding, content_type); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:23
    def reset!; end

    # pkg:gem/httplog#lib/httplog/http_log.rb:173
    def transform_response_code(response_code_name); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:51
    def url_approved?(url); end

    private

    # pkg:gem/httplog#lib/httplog/http_log.rb:207
    def dump_json(data); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:328
    def hash_classes; end

    # pkg:gem/httplog#lib/httplog/http_log.rb:227
    def json_payload(data = T.unsafe(nil)); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:354
    def log_data_lines(data); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:211
    def log_graylog(data); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:193
    def log_json(data = T.unsafe(nil)); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:257
    def masked(msg, key = T.unsafe(nil)); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:304
    def masked_data(msg); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:283
    def parse_request(options); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:364
    def prefix; end

    # pkg:gem/httplog#lib/httplog/http_log.rb:222
    def send_to_graylog(data); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:315
    def string_classes; end

    # pkg:gem/httplog#lib/httplog/http_log.rb:346
    def text_based?(content_type); end

    # pkg:gem/httplog#lib/httplog/http_log.rb:336
    def utf_encoded(data, content_type = T.unsafe(nil)); end
  end
end

# pkg:gem/httplog#lib/httplog/http_log.rb:13
class HttpLog::BodyParsingError < ::StandardError; end

# pkg:gem/httplog#lib/httplog/configuration.rb:4
class HttpLog::Configuration
  # pkg:gem/httplog#lib/httplog/configuration.rb:30
  def initialize; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def color; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def color=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def compact_log; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def compact_log=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def enabled; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def enabled=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def filter_parameters; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def filter_parameters=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def graylog_formatter; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def graylog_formatter=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def json_log; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def json_log=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def json_parser; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def json_parser=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_benchmark; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_benchmark=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_connect; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_connect=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_data; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_data=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_headers; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_headers=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_request; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_request=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_response; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_response=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_status; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def log_status=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def logger; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def logger=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def logger_method; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def logger_method=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def prefix; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def prefix=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def prefix_data_lines; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def prefix_data_lines=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def prefix_line_numbers; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def prefix_line_numbers=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def prefix_response_lines; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def prefix_response_lines=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def severity; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def severity=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def url_allowlist_pattern; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def url_allowlist_pattern=(_arg0); end

  # Backward compatibility aliases to version prior to 1.7.2
  #
  # pkg:gem/httplog#lib/httplog/configuration.rb:58
  def url_blacklist_pattern; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:59
  def url_blacklist_pattern=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def url_denylist_pattern; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def url_denylist_pattern=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def url_masked_body_pattern; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:5
  def url_masked_body_pattern=(_arg0); end

  # pkg:gem/httplog#lib/httplog/configuration.rb:60
  def url_whitelist_pattern; end

  # pkg:gem/httplog#lib/httplog/configuration.rb:61
  def url_whitelist_pattern=(_arg0); end
end

# pkg:gem/httplog#lib/httplog/http_log.rb:10
HttpLog::LOG_PREFIX = T.let(T.unsafe(nil), String)

# pkg:gem/httplog#lib/httplog/http_log.rb:11
HttpLog::PARAM_MASK = T.let(T.unsafe(nil), String)

# pkg:gem/httplog#lib/httplog/version.rb:4
HttpLog::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/httplog#lib/httplog/adapters/net_http.rb:4
class Net::HTTP < ::Net::Protocol
  # pkg:gem/httplog#lib/httplog/adapters/net_http.rb:44
  def connect; end

  # pkg:gem/httplog#lib/httplog/adapters/net_http.rb:5
  def orig_request(*args, &block); end

  # pkg:gem/httplog#lib/httplog/adapters/net_http.rb:8
  def request(req, body = T.unsafe(nil), &block); end

  private

  # pkg:gem/httplog#lib/httplog/adapters/net_http.rb:6
  def orig_connect; end
end
