# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `listen` gem.
# Please instead update this file by running `bin/tapioca gem listen`.


# Code copied from https://github.com/celluloid/celluloid-fsm
#
# pkg:gem/listen#lib/listen/logger.rb:3
module Listen
  class << self
    # pkg:gem/listen#lib/listen/logger.rb:19
    def adapter_warn(message); end

    # Returns the value of attribute adapter_warn_behavior.
    #
    # pkg:gem/listen#lib/listen/logger.rb:13
    def adapter_warn_behavior; end

    # Sets the attribute adapter_warn_behavior
    #
    # @param value the value to set the attribute adapter_warn_behavior to.
    #
    # pkg:gem/listen#lib/listen/logger.rb:13
    def adapter_warn_behavior=(_arg0); end

    # pkg:gem/listen#lib/listen/logger.rb:15
    def logger; end

    # Sets the attribute logger
    #
    # @param value the value to set the attribute logger to.
    #
    # pkg:gem/listen#lib/listen/logger.rb:12
    def logger=(_arg0); end

    # This is used by the `listen` binary to handle Ctrl-C
    #
    # pkg:gem/listen#lib/listen.rb:37
    def stop; end

    # Listens to file system modifications on a either single directory or
    # multiple directories.
    #
    # @return [Listen::Listener] the listener
    # @yield [modified, added, removed] the changed files
    # @yieldparam added [Array<String>] the list of added files
    # @yieldparam modified [Array<String>] the list of modified files
    # @yieldparam removed [Array<String>] the list of removed files
    #
    # pkg:gem/listen#lib/listen.rb:29
    def to(*args, &block); end

    private

    # pkg:gem/listen#lib/listen/logger.rb:50
    def adapter_warn_behavior_callback(message); end

    # pkg:gem/listen#lib/listen/logger.rb:32
    def default_logger; end
  end
end

# pkg:gem/listen#lib/listen/adapter/base.rb:9
module Listen::Adapter
  class << self
    # pkg:gem/listen#lib/listen/adapter.rb:17
    def select(options = T.unsafe(nil)); end

    private

    # pkg:gem/listen#lib/listen/adapter.rb:33
    def _usable_adapter_class; end

    # pkg:gem/listen#lib/listen/adapter.rb:37
    def _warn_polling_fallback(options); end
  end
end

# pkg:gem/listen#lib/listen/adapter/bsd.rb:9
class Listen::Adapter::BSD < ::Listen::Adapter::Base
  private

  # pkg:gem/listen#lib/listen/adapter/bsd.rb:70
  def _change(event_flags); end

  # pkg:gem/listen#lib/listen/adapter/bsd.rb:40
  def _configure(directory, &callback); end

  # pkg:gem/listen#lib/listen/adapter/bsd.rb:79
  def _event_path(event); end

  # Quick rubocop workaround
  #
  # pkg:gem/listen#lib/listen/adapter/bsd.rb:99
  def _find(*paths, &block); end

  # pkg:gem/listen#lib/listen/adapter/bsd.rb:52
  def _process_event(dir, event); end

  # pkg:gem/listen#lib/listen/adapter/bsd.rb:48
  def _run; end

  # pkg:gem/listen#lib/listen/adapter/bsd.rb:92
  def _watch_file(path, queue); end

  # pkg:gem/listen#lib/listen/adapter/bsd.rb:83
  def _watch_for_new_file(event); end

  class << self
    # @return [Boolean]
    #
    # pkg:gem/listen#lib/listen/adapter/bsd.rb:28
    def usable?; end
  end
end

# pkg:gem/listen#lib/listen/adapter/bsd.rb:23
Listen::Adapter::BSD::BUNDLER_DECLARE_GEM = T.let(T.unsafe(nil), String)

# pkg:gem/listen#lib/listen/adapter/bsd.rb:12
Listen::Adapter::BSD::DEFAULTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/listen#lib/listen/adapter/bsd.rb:10
Listen::Adapter::BSD::OS_REGEXP = T.let(T.unsafe(nil), Regexp)

# pkg:gem/listen#lib/listen/adapter/base.rb:10
class Listen::Adapter::Base
  # @return [Base] a new instance of Base
  #
  # pkg:gem/listen#lib/listen/adapter/base.rb:16
  def initialize(config); end

  # Returns the value of attribute config.
  #
  # pkg:gem/listen#lib/listen/adapter/base.rb:11
  def config; end

  # TODO: it's a separate method as a temporary workaround for tests
  #
  # pkg:gem/listen#lib/listen/adapter/base.rb:33
  def configure; end

  # Returns the value of attribute options.
  #
  # pkg:gem/listen#lib/listen/adapter/base.rb:11
  def options; end

  # pkg:gem/listen#lib/listen/adapter/base.rb:65
  def start; end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/adapter/base.rb:61
  def started?; end

  # pkg:gem/listen#lib/listen/adapter/base.rb:83
  def stop; end

  private

  # pkg:gem/listen#lib/listen/adapter/base.rb:111
  def _log_exception(msg, caller_stack); end

  # TODO: allow backend adapters to pass specific invalidation objects
  # e.g. Darwin -> DirRescan, INotify -> MoveScan, etc.
  #
  # pkg:gem/listen#lib/listen/adapter/base.rb:107
  def _queue_change(type, dir, rel_path, options); end

  # pkg:gem/listen#lib/listen/adapter/base.rb:90
  def _stop; end

  # pkg:gem/listen#lib/listen/adapter/base.rb:95
  def _timed(title); end

  class << self
    # @return [Boolean]
    #
    # pkg:gem/listen#lib/listen/adapter/base.rb:123
    def usable?; end
  end
end

# TODO: only used by tests
#
# pkg:gem/listen#lib/listen/adapter/base.rb:14
Listen::Adapter::Base::DEFAULTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/listen#lib/listen/adapter/config.rb:7
class Listen::Adapter::Config
  # @return [Config] a new instance of Config
  #
  # pkg:gem/listen#lib/listen/adapter/config.rb:10
  def initialize(directories, queue, silencer, adapter_options); end

  # Returns the value of attribute adapter_options.
  #
  # pkg:gem/listen#lib/listen/adapter/config.rb:8
  def adapter_options; end

  # Returns the value of attribute directories.
  #
  # pkg:gem/listen#lib/listen/adapter/config.rb:8
  def directories; end

  # Returns the value of attribute queue.
  #
  # pkg:gem/listen#lib/listen/adapter/config.rb:8
  def queue; end

  # Returns the value of attribute silencer.
  #
  # pkg:gem/listen#lib/listen/adapter/config.rb:8
  def silencer; end
end

# Adapter implementation for Mac OS X `FSEvents`.
#
# pkg:gem/listen#lib/listen/adapter/darwin.rb:9
class Listen::Adapter::Darwin < ::Listen::Adapter::Base
  private

  # pkg:gem/listen#lib/listen/adapter/darwin.rb:39
  def _configure(dir, &callback); end

  # pkg:gem/listen#lib/listen/adapter/darwin.rb:52
  def _process_changes(dirs); end

  # pkg:gem/listen#lib/listen/adapter/darwin.rb:64
  def _process_event(dir, path); end

  # pkg:gem/listen#lib/listen/adapter/darwin.rb:43
  def _run; end

  # pkg:gem/listen#lib/listen/adapter/darwin.rb:71
  def _stop; end

  class << self
    # @return [Boolean]
    #
    # pkg:gem/listen#lib/listen/adapter/darwin.rb:25
    def usable?; end
  end
end

# The default delay between checking for changes.
#
# pkg:gem/listen#lib/listen/adapter/darwin.rb:13
Listen::Adapter::Darwin::DEFAULTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/listen#lib/listen/adapter/darwin.rb:15
Listen::Adapter::Darwin::INCOMPATIBLE_GEM_VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/listen#lib/listen/adapter/darwin.rb:10
Listen::Adapter::Darwin::OS_REGEXP = T.let(T.unsafe(nil), Regexp)

# @see https://github.com/nex3/rb-inotify
#
# pkg:gem/listen#lib/listen/adapter/linux.rb:6
class Listen::Adapter::Linux < ::Listen::Adapter::Base
  private

  # pkg:gem/listen#lib/listen/adapter/linux.rb:86
  def _change(event_flags); end

  # pkg:gem/listen#lib/listen/adapter/linux.rb:27
  def _configure(directory, &callback); end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/adapter/linux.rb:97
  def _dir_event?(event); end

  # pkg:gem/listen#lib/listen/adapter/linux.rb:42
  def _process_event(dir, event); end

  # pkg:gem/listen#lib/listen/adapter/linux.rb:37
  def _run; end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/adapter/linux.rb:76
  def _skip_event?(event); end

  # pkg:gem/listen#lib/listen/adapter/linux.rb:101
  def _stop; end
end

# pkg:gem/listen#lib/listen/adapter/linux.rb:9
Listen::Adapter::Linux::DEFAULTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/listen#lib/listen/adapter/linux.rb:7
Listen::Adapter::Linux::OS_REGEXP = T.let(T.unsafe(nil), Regexp)

# pkg:gem/listen#lib/listen/adapter/linux.rb:24
Listen::Adapter::Linux::README_URL = T.let(T.unsafe(nil), String)

# pkg:gem/listen#lib/listen/adapter.rb:12
Listen::Adapter::OPTIMIZED_ADAPTERS = T.let(T.unsafe(nil), Array)

# pkg:gem/listen#lib/listen/adapter.rb:13
Listen::Adapter::POLLING_FALLBACK_MESSAGE = T.let(T.unsafe(nil), String)

# Polling Adapter that works cross-platform and
# has no dependencies. This is the adapter that
# uses the most CPU processing power and has higher
# file IO than the other implementations.
#
# pkg:gem/listen#lib/listen/adapter/polling.rb:10
class Listen::Adapter::Polling < ::Listen::Adapter::Base
  private

  # pkg:gem/listen#lib/listen/adapter/polling.rb:17
  def _configure(_, &callback); end

  # pkg:gem/listen#lib/listen/adapter/polling.rb:35
  def _process_event(dir, _); end

  # pkg:gem/listen#lib/listen/adapter/polling.rb:22
  def _run; end
end

# pkg:gem/listen#lib/listen/adapter/polling.rb:13
Listen::Adapter::Polling::DEFAULTS = T.let(T.unsafe(nil), Hash)

# match every OS
#
# pkg:gem/listen#lib/listen/adapter/polling.rb:11
Listen::Adapter::Polling::OS_REGEXP = T.let(T.unsafe(nil), Regexp)

# Adapter implementation for Windows `wdm`.
#
# pkg:gem/listen#lib/listen/adapter/windows.rb:7
class Listen::Adapter::Windows < ::Listen::Adapter::Base
  private

  # pkg:gem/listen#lib/listen/adapter/windows.rb:87
  def _change(type); end

  # pkg:gem/listen#lib/listen/adapter/windows.rb:29
  def _configure(dir); end

  # pkg:gem/listen#lib/listen/adapter/windows.rb:51
  def _process_event(dir, event); end

  # pkg:gem/listen#lib/listen/adapter/windows.rb:46
  def _run; end

  class << self
    # @return [Boolean]
    #
    # pkg:gem/listen#lib/listen/adapter/windows.rb:15
    def usable?; end
  end
end

# pkg:gem/listen#lib/listen/adapter/windows.rb:10
Listen::Adapter::Windows::BUNDLER_DECLARE_GEM = T.let(T.unsafe(nil), String)

# pkg:gem/listen#lib/listen/adapter/windows.rb:8
Listen::Adapter::Windows::OS_REGEXP = T.let(T.unsafe(nil), Regexp)

# pkg:gem/listen#lib/listen/backend.rb:12
class Listen::Backend
  extend ::Forwardable

  # @return [Backend] a new instance of Backend
  #
  # pkg:gem/listen#lib/listen/backend.rb:15
  def initialize(directories, queue, silencer, config); end

  # Returns the value of attribute min_delay_between_events.
  #
  # pkg:gem/listen#lib/listen/backend.rb:34
  def min_delay_between_events; end

  # pkg:gem/listen#lib/listen/backend.rb:31
  def start(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/listen#lib/listen/backend.rb:32
  def stop(*_arg0, **_arg1, &_arg2); end

  private

  # Returns the value of attribute adapter.
  #
  # pkg:gem/listen#lib/listen/backend.rb:38
  def adapter; end
end

# TODO: rename to Snapshot
#
# pkg:gem/listen#lib/listen/change.rb:8
class Listen::Change
  # @return [Change] a new instance of Change
  #
  # pkg:gem/listen#lib/listen/change.rb:27
  def initialize(config, record); end

  # Invalidate some part of the snapshot/record (dir, file, subtree, etc.)
  #
  # pkg:gem/listen#lib/listen/change.rb:36
  def invalidate(type, rel_path, options); end

  # Returns the value of attribute record.
  #
  # pkg:gem/listen#lib/listen/change.rb:25
  def record; end
end

# TODO: test this class for coverage
#
# pkg:gem/listen#lib/listen/change.rb:10
class Listen::Change::Config
  # @return [Config] a new instance of Config
  #
  # pkg:gem/listen#lib/listen/change.rb:11
  def initialize(queue, silencer); end

  # pkg:gem/listen#lib/listen/change.rb:20
  def queue(*args); end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/change.rb:16
  def silenced?(path, type); end
end

# TODO: refactor (turn it into a normal object, cache the stat, etc)
#
# pkg:gem/listen#lib/listen/directory.rb:7
class Listen::Directory
  class << self
    # pkg:gem/listen#lib/listen/directory.rb:62
    def _async_changes(snapshot, path, previous, options); end

    # pkg:gem/listen#lib/listen/directory.rb:72
    def _change(snapshot, type, path, options); end

    # pkg:gem/listen#lib/listen/directory.rb:82
    def _children(path); end

    # @return [Boolean]
    #
    # pkg:gem/listen#lib/listen/directory.rb:56
    def ascendant_of?(base, other); end

    # pkg:gem/listen#lib/listen/directory.rb:9
    def scan(snapshot, rel_path, options); end
  end
end

# pkg:gem/listen#lib/listen/error.rb:6
class Listen::Error < ::RuntimeError; end

# pkg:gem/listen#lib/listen/error.rb:9
class Listen::Error::INotifyMaxWatchesExceeded < ::Listen::Error; end

# pkg:gem/listen#lib/listen/error.rb:7
class Listen::Error::NotStarted < ::Listen::Error; end

# pkg:gem/listen#lib/listen/error.rb:8
class Listen::Error::SymlinkLoop < ::Listen::Error; end

# pkg:gem/listen#lib/listen/event/processor.rb:6
module Listen::Event; end

# pkg:gem/listen#lib/listen/event/config.rb:5
class Listen::Event::Config
  # @return [Config] a new instance of Config
  #
  # pkg:gem/listen#lib/listen/event/config.rb:8
  def initialize(listener, event_queue, queue_optimizer, wait_for_delay, &block); end

  # pkg:gem/listen#lib/listen/event/config.rb:26
  def call(*args); end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/event/config.rb:30
  def callable?; end

  # Returns the value of attribute event_queue.
  #
  # pkg:gem/listen#lib/listen/event/config.rb:6
  def event_queue; end

  # Returns the value of attribute listener.
  #
  # pkg:gem/listen#lib/listen/event/config.rb:6
  def listener; end

  # Returns the value of attribute min_delay_between_events.
  #
  # pkg:gem/listen#lib/listen/event/config.rb:6
  def min_delay_between_events; end

  # pkg:gem/listen#lib/listen/event/config.rb:34
  def optimize_changes(changes); end

  # pkg:gem/listen#lib/listen/event/config.rb:22
  def sleep(seconds); end
end

# pkg:gem/listen#lib/listen/event/loop.rb:10
class Listen::Event::Loop
  include ::Listen::FSM
  extend ::Listen::FSM::ClassMethods

  # @return [Loop] a new instance of Loop
  #
  # pkg:gem/listen#lib/listen/event/loop.rb:22
  def initialize(config); end

  # pkg:gem/listen#lib/listen/event/loop.rb:60
  def pause; end

  # pkg:gem/listen#lib/listen/event/loop.rb:42
  def start; end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/event/loop.rb:35
  def started?; end

  # pkg:gem/listen#lib/listen/event/loop.rb:65
  def stop; end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/event/loop.rb:72
  def stopped?; end

  # pkg:gem/listen#lib/listen/event/loop.rb:29
  def wakeup_on_event; end

  private

  # pkg:gem/listen#lib/listen/event/loop.rb:78
  def _process_changes; end

  # pkg:gem/listen#lib/listen/event/loop.rb:86
  def _wakeup(reason); end
end

# pkg:gem/listen#lib/listen/event/loop.rb:13
Listen::Event::Loop::Error = Listen::Error

# pkg:gem/listen#lib/listen/event/loop.rb:39
Listen::Event::Loop::MAX_STARTUP_SECONDS = T.let(T.unsafe(nil), Float)

# for backward compatibility
#
# pkg:gem/listen#lib/listen/event/loop.rb:14
Listen::Event::Loop::NotStarted = Listen::Error::NotStarted

# pkg:gem/listen#lib/listen/event/processor.rb:7
class Listen::Event::Processor
  # @return [Processor] a new instance of Processor
  #
  # pkg:gem/listen#lib/listen/event/processor.rb:8
  def initialize(config, reasons); end

  # TODO: implement this properly instead of checking the state at arbitrary
  # points in time
  #
  # pkg:gem/listen#lib/listen/event/processor.rb:17
  def loop_for(latency); end

  private

  # pkg:gem/listen#lib/listen/event/processor.rb:55
  def _check_stopped; end

  # pkg:gem/listen#lib/listen/event/processor.rb:82
  def _deadline; end

  # pkg:gem/listen#lib/listen/event/processor.rb:96
  def _flush_wakeup_reasons; end

  # for easier testing without sleep loop
  #
  # pkg:gem/listen#lib/listen/event/processor.rb:104
  def _process_changes(event); end

  # pkg:gem/listen#lib/listen/event/processor.rb:74
  def _remember_time_of_first_unprocessed_event; end

  # pkg:gem/listen#lib/listen/event/processor.rb:78
  def _reset_no_unprocessed_events; end

  # pkg:gem/listen#lib/listen/event/processor.rb:62
  def _sleep(seconds); end

  # blocks until event is popped
  # returns the event or `nil` when the event_queue is closed
  #
  # pkg:gem/listen#lib/listen/event/processor.rb:89
  def _wait_until_events; end

  # pkg:gem/listen#lib/listen/event/processor.rb:36
  def _wait_until_events_calm_down; end

  # pkg:gem/listen#lib/listen/event/processor.rb:51
  def _wait_until_no_longer_paused; end

  # Returns the value of attribute config.
  #
  # pkg:gem/listen#lib/listen/event/processor.rb:125
  def config; end
end

# pkg:gem/listen#lib/listen/event/processor.rb:33
class Listen::Event::Processor::Stopped < ::RuntimeError; end

# pkg:gem/listen#lib/listen/event/queue.rb:7
class Listen::Event::Queue
  extend ::Forwardable

  # @return [Queue] a new instance of Queue
  #
  # pkg:gem/listen#lib/listen/event/queue.rb:20
  def initialize(config); end

  # pkg:gem/listen#lib/listen/event/queue.rb:25
  def <<(args); end

  # pkg:gem/listen#lib/listen/event/queue.rb:41
  def close(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/listen#lib/listen/event/queue.rb:39
  def empty?(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/listen#lib/listen/event/queue.rb:40
  def pop(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/listen#lib/listen/event/queue.rb:45
  def _safe_relative_from_cwd(dir); end
end

# pkg:gem/listen#lib/listen/event/queue.rb:10
class Listen::Event::Queue::Config
  # @return [Config] a new instance of Config
  #
  # pkg:gem/listen#lib/listen/event/queue.rb:11
  def initialize(relative); end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/event/queue.rb:15
  def relative?; end
end

# pkg:gem/listen#lib/listen/fsm.rb:6
module Listen::FSM
  mixes_in_class_methods ::Listen::FSM::ClassMethods

  # NOTE: including classes must call initialize_fsm from their initialize method.
  #
  # pkg:gem/listen#lib/listen/fsm.rb:40
  def initialize_fsm; end

  # Current state of the FSM, stored as a symbol
  #
  # pkg:gem/listen#lib/listen/fsm.rb:48
  def state; end

  # checks for one of the given states to wait for
  # if not already, waits for a state change (up to timeout seconds--`nil` means infinite)
  # returns truthy iff the transition to one of the desired state has occurred
  #
  # pkg:gem/listen#lib/listen/fsm.rb:53
  def wait_for_state(*wait_for_states, timeout: T.unsafe(nil)); end

  private

  # pkg:gem/listen#lib/listen/fsm.rb:106
  def current_state; end

  # pkg:gem/listen#lib/listen/fsm.rb:67
  def transition(new_state_name); end

  # Low-level, immediate state transition with no checks or callbacks.
  #
  # pkg:gem/listen#lib/listen/fsm.rb:75
  def transition!(new_state_name); end

  # pkg:gem/listen#lib/listen/fsm.rb:101
  def transition_with_callbacks!(new_state); end

  # pkg:gem/listen#lib/listen/fsm.rb:85
  def validate_and_sanitize_new_state(new_state_name); end

  class << self
    # Included hook to extend class methods
    #
    # pkg:gem/listen#lib/listen/fsm.rb:8
    def included(klass); end
  end
end

# pkg:gem/listen#lib/listen/fsm.rb:12
module Listen::FSM::ClassMethods
  # Obtain or set the start state
  # Passing a state name sets the start state
  #
  # pkg:gem/listen#lib/listen/fsm.rb:15
  def start_state(new_start_state = T.unsafe(nil)); end

  # Declare an FSM state and optionally provide a callback block to fire on state entry
  # Options:
  # * to: a state or array of states this state can transition to
  #
  # pkg:gem/listen#lib/listen/fsm.rb:33
  def state(state_name, to: T.unsafe(nil), &block); end

  # The valid states for this FSM, as a hash with state name symbols as keys and State objects as values.
  #
  # pkg:gem/listen#lib/listen/fsm.rb:26
  def states; end
end

# pkg:gem/listen#lib/listen/fsm.rb:110
class Listen::FSM::State
  # @return [State] a new instance of State
  #
  # pkg:gem/listen#lib/listen/fsm.rb:113
  def initialize(name, transitions, &block); end

  # pkg:gem/listen#lib/listen/fsm.rb:121
  def call(obj); end

  # Returns the value of attribute name.
  #
  # pkg:gem/listen#lib/listen/fsm.rb:111
  def name; end

  # Returns the value of attribute transitions.
  #
  # pkg:gem/listen#lib/listen/fsm.rb:111
  def transitions; end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/fsm.rb:125
  def valid_transition?(new_state); end
end

# pkg:gem/listen#lib/listen/file.rb:6
class Listen::File
  class << self
    # pkg:gem/listen#lib/listen/file.rb:10
    def change(record, rel_path); end

    # @return [Boolean]
    #
    # pkg:gem/listen#lib/listen/file.rb:86
    def inaccurate_mac_time?(stat); end
  end
end

# pkg:gem/listen#lib/listen/listener/config.rb:4
class Listen::Listener
  include ::Listen::FSM
  extend ::Listen::FSM::ClassMethods

  # Initializes the directories listener.
  #
  #
  # @param directory [String] the directories to listen to
  # @param options [Hash] the listen options (see Listen::Listener::Options)
  # @return [Listener] a new instance of Listener
  # @yield [modified, added, removed] the changed files
  # @yieldparam added [Array<String>] the list of added files
  # @yieldparam modified [Array<String>] the list of modified files
  # @yieldparam removed [Array<String>] the list of removed files
  #
  # pkg:gem/listen#lib/listen/listener.rb:37
  def initialize(*dirs, &block); end

  # pkg:gem/listen#lib/listen/listener.rb:124
  def ignore(regexps); end

  # pkg:gem/listen#lib/listen/listener.rb:128
  def ignore!(regexps); end

  # pkg:gem/listen#lib/listen/listener.rb:132
  def only(regexps); end

  # Stops invoking callbacks (messages pile up)
  #
  # pkg:gem/listen#lib/listen/listener.rb:107
  def pause; end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/listener.rb:116
  def paused?; end

  # processing means callbacks are called
  #
  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/listener.rb:112
  def processing?; end

  # Starts processing events and starts adapters
  # or resumes invoking callbacks if paused
  #
  # pkg:gem/listen#lib/listen/listener.rb:89
  def start; end

  # Stops both listening for events and processing them
  #
  # pkg:gem/listen#lib/listen/listener.rb:102
  def stop; end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/listener.rb:120
  def stopped?; end
end

# pkg:gem/listen#lib/listen/listener/config.rb:5
class Listen::Listener::Config
  # @return [Config] a new instance of Config
  #
  # pkg:gem/listen#lib/listen/listener/config.rb:17
  def initialize(opts); end

  # pkg:gem/listen#lib/listen/listener/config.rb:30
  def adapter_instance_options(klass); end

  # pkg:gem/listen#lib/listen/listener/config.rb:35
  def adapter_select_options; end

  # Returns the value of attribute min_delay_between_events.
  #
  # pkg:gem/listen#lib/listen/listener/config.rb:28
  def min_delay_between_events; end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/listener/config.rb:24
  def relative?; end

  # Returns the value of attribute silencer_rules.
  #
  # pkg:gem/listen#lib/listen/listener/config.rb:28
  def silencer_rules; end
end

# pkg:gem/listen#lib/listen/listener/config.rb:6
Listen::Listener::Config::DEFAULTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/listen#lib/listen/monotonic_time.rb:4
module Listen::MonotonicTime
  class << self
    # pkg:gem/listen#lib/listen/monotonic_time.rb:8
    def now; end
  end
end

# pkg:gem/listen#lib/listen/options.rb:4
class Listen::Options
  # @return [Options] a new instance of Options
  #
  # pkg:gem/listen#lib/listen/options.rb:5
  def initialize(opts, defaults); end

  # pkg:gem/listen#lib/listen/options.rb:19
  def method_missing(name, *_); end

  private

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/options.rb:15
  def respond_to_missing?(name, *_); end
end

# pkg:gem/listen#lib/listen/queue_optimizer.rb:4
class Listen::QueueOptimizer
  # @return [QueueOptimizer] a new instance of QueueOptimizer
  #
  # pkg:gem/listen#lib/listen/queue_optimizer.rb:32
  def initialize(config); end

  # pkg:gem/listen#lib/listen/queue_optimizer.rb:24
  def smoosh_changes(changes); end

  private

  # pkg:gem/listen#lib/listen/queue_optimizer.rb:69
  def _calculate_add_remove_difference(actions, path, default_if_exists); end

  # pkg:gem/listen#lib/listen/queue_optimizer.rb:61
  def _logical_action_for(path, actions); end

  # remove extraneous rb-inotify events, keeping them only if it's a possible
  # editor rename() call (e.g. Kate and Sublime)
  #
  # pkg:gem/listen#lib/listen/queue_optimizer.rb:91
  def _reinterpret_related_changes(cookies); end

  # groups changes into the expected structure expected by
  # clients
  #
  # pkg:gem/listen#lib/listen/queue_optimizer.rb:42
  def _squash_changes(changes); end

  # Returns the value of attribute config.
  #
  # pkg:gem/listen#lib/listen/queue_optimizer.rb:38
  def config; end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/queue_optimizer.rb:107
  def editor_modified?(changes); end
end

# pkg:gem/listen#lib/listen/queue_optimizer.rb:5
class Listen::QueueOptimizer::Config
  # @return [Config] a new instance of Config
  #
  # pkg:gem/listen#lib/listen/queue_optimizer.rb:6
  def initialize(adapter_class, silencer); end

  # pkg:gem/listen#lib/listen/queue_optimizer.rb:19
  def debug(*args, &block); end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/queue_optimizer.rb:11
  def exist?(path); end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/queue_optimizer.rb:15
  def silenced?(path, type); end
end

# @private api
#
# pkg:gem/listen#lib/listen/record/entry.rb:5
class Listen::Record
  # @return [Record] a new instance of Record
  #
  # pkg:gem/listen#lib/listen/record.rb:13
  def initialize(directory, silencer); end

  # pkg:gem/listen#lib/listen/record.rb:19
  def add_dir(rel_path); end

  # pkg:gem/listen#lib/listen/record.rb:61
  def build; end

  # pkg:gem/listen#lib/listen/record.rb:45
  def dir_entries(rel_path); end

  # pkg:gem/listen#lib/listen/record.rb:35
  def file_data(rel_path); end

  # TODO: one Record object per watched directory?
  # TODO: deprecate
  #
  # pkg:gem/listen#lib/listen/record.rb:11
  def root; end

  # pkg:gem/listen#lib/listen/record.rb:30
  def unset_path(rel_path); end

  # pkg:gem/listen#lib/listen/record.rb:25
  def update_file(rel_path, data); end

  private

  # pkg:gem/listen#lib/listen/record.rb:102
  def _fast_build_dir(remaining, symlink_detector); end

  # pkg:gem/listen#lib/listen/record.rb:116
  def _fast_try_file(entry); end

  # pkg:gem/listen#lib/listen/record.rb:90
  def _fast_unset_path(dirname, basename); end

  # pkg:gem/listen#lib/listen/record.rb:82
  def _fast_update_file(dirname, basename, data); end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/record.rb:74
  def empty_dirname?(dirname); end

  # pkg:gem/listen#lib/listen/record.rb:78
  def reset_tree; end
end

# Represents a directory entry (dir or file)
#
# pkg:gem/listen#lib/listen/record/entry.rb:7
class Listen::Record::Entry
  # file: "/home/me/watched_dir", "app/models", "foo.rb"
  # dir, "/home/me/watched_dir", "."
  #
  # @return [Entry] a new instance of Entry
  #
  # pkg:gem/listen#lib/listen/record/entry.rb:10
  def initialize(root, relative, name = T.unsafe(nil)); end

  # pkg:gem/listen#lib/listen/record/entry.rb:18
  def children; end

  # pkg:gem/listen#lib/listen/record/entry.rb:25
  def meta; end

  # Returns the value of attribute name.
  #
  # pkg:gem/listen#lib/listen/record/entry.rb:16
  def name; end

  # pkg:gem/listen#lib/listen/record/entry.rb:43
  def real_path; end

  # record hash is e.g.
  # if @record["/home/me/watched_dir"]["project/app/models"]["foo.rb"]
  # if @record["/home/me/watched_dir"]["project/app"]["models"]
  # record_dir_key is "project/app/models"
  #
  # pkg:gem/listen#lib/listen/record/entry.rb:34
  def record_dir_key; end

  # Returns the value of attribute relative.
  #
  # pkg:gem/listen#lib/listen/record/entry.rb:16
  def relative; end

  # Returns the value of attribute root.
  #
  # pkg:gem/listen#lib/listen/record/entry.rb:16
  def root; end

  # pkg:gem/listen#lib/listen/record/entry.rb:38
  def sys_path; end

  private

  # @raise [Errno::ENOTDIR]
  #
  # pkg:gem/listen#lib/listen/record/entry.rb:54
  def _entries(dir); end

  # pkg:gem/listen#lib/listen/record/entry.rb:49
  def _join; end
end

# pkg:gem/listen#lib/listen/record/symlink_detector.rb:9
class Listen::Record::SymlinkDetector
  # @return [SymlinkDetector] a new instance of SymlinkDetector
  #
  # pkg:gem/listen#lib/listen/record/symlink_detector.rb:24
  def initialize; end

  # pkg:gem/listen#lib/listen/record/symlink_detector.rb:28
  def verify_unwatched!(entry); end

  # Leaving this stub here since some warning work-arounds were referring to it.
  # Deprecated. Will be removed in Listen v4.0.
  #
  # pkg:gem/listen#lib/listen/record/symlink_detector.rb:35
  def warn(message); end

  private

  # @raise [::Listen::Error::SymlinkLoop]
  #
  # pkg:gem/listen#lib/listen/record/symlink_detector.rb:41
  def _fail(symlinked, real_path); end
end

# for backward compatibility
#
# pkg:gem/listen#lib/listen/record/symlink_detector.rb:22
Listen::Record::SymlinkDetector::Error = Listen::Error

# pkg:gem/listen#lib/listen/record/symlink_detector.rb:10
Listen::Record::SymlinkDetector::README_URL = T.let(T.unsafe(nil), String)

# pkg:gem/listen#lib/listen/record/symlink_detector.rb:12
Listen::Record::SymlinkDetector::SYMLINK_LOOP_ERROR = T.let(T.unsafe(nil), String)

# pkg:gem/listen#lib/listen/silencer.rb:4
class Listen::Silencer
  # @return [Silencer] a new instance of Silencer
  #
  # pkg:gem/listen#lib/listen/silencer.rb:67
  def initialize(**options); end

  # TODO: deprecate this mutator
  #
  # pkg:gem/listen#lib/listen/silencer.rb:72
  def configure(options); end

  # TODO: deprecate these mutators; use attr_reader instead
  #
  # pkg:gem/listen#lib/listen/silencer.rb:65
  def ignore_patterns; end

  # TODO: deprecate these mutators; use attr_reader instead
  #
  # pkg:gem/listen#lib/listen/silencer.rb:65
  def ignore_patterns=(_arg0); end

  # TODO: deprecate these mutators; use attr_reader instead
  #
  # pkg:gem/listen#lib/listen/silencer.rb:65
  def only_patterns; end

  # TODO: deprecate these mutators; use attr_reader instead
  #
  # pkg:gem/listen#lib/listen/silencer.rb:65
  def only_patterns=(_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/silencer.rb:77
  def silenced?(relative_path, type); end

  private

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/silencer.rb:85
  def _ignore?(path); end

  # pkg:gem/listen#lib/listen/silencer.rb:93
  def _init_ignores(ignores, overrides); end

  # @return [Boolean]
  #
  # pkg:gem/listen#lib/listen/silencer.rb:89
  def _only?(path); end
end

# pkg:gem/listen#lib/listen/silencer/controller.rb:5
class Listen::Silencer::Controller
  # @return [Controller] a new instance of Controller
  #
  # pkg:gem/listen#lib/listen/silencer/controller.rb:6
  def initialize(silencer, default_options); end

  # pkg:gem/listen#lib/listen/silencer/controller.rb:19
  def append_ignores(*regexps); end

  # pkg:gem/listen#lib/listen/silencer/controller.rb:24
  def replace_with_bang_ignores(regexps); end

  # pkg:gem/listen#lib/listen/silencer/controller.rb:28
  def replace_with_only(regexps); end

  private

  # pkg:gem/listen#lib/listen/silencer/controller.rb:34
  def _reconfigure_silencer(extra_options); end
end

# The default list of files that get ignored.
#
# pkg:gem/listen#lib/listen/silencer.rb:24
Listen::Silencer::DEFAULT_IGNORED_EXTENSIONS = T.let(T.unsafe(nil), Regexp)

# The default list of directories that get ignored.
#
# pkg:gem/listen#lib/listen/silencer.rb:6
Listen::Silencer::DEFAULT_IGNORED_FILES = T.let(T.unsafe(nil), Regexp)

# pkg:gem/listen#lib/listen/thread.rb:8
module Listen::Thread
  class << self
    # Creates a new thread with the given name.
    # Any exceptions raised by the thread will be logged with the thread name and complete backtrace.
    #
    # pkg:gem/listen#lib/listen/thread.rb:13
    def new(name, &block); end

    # pkg:gem/listen#lib/listen/thread.rb:25
    def rescue_and_log(method_name, *args, caller_stack: T.unsafe(nil)); end

    private

    # pkg:gem/listen#lib/listen/thread.rb:43
    def _exception_with_causes(exception); end

    # pkg:gem/listen#lib/listen/thread.rb:33
    def _log_exception(exception, thread_name, caller_stack: T.unsafe(nil)); end
  end
end

# pkg:gem/listen#lib/listen/version.rb:4
Listen::VERSION = T.let(T.unsafe(nil), String)
