# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `orm_adapter` gem.
# Please instead update this file by running `bin/tapioca gem orm_adapter`.


# source://orm_adapter//lib/orm_adapter/adapters/mongoid.rb#3
module Mongoid
  extend ::Mongoid::GlobalDiscriminatorKeyAssignment
end

# source://orm_adapter//lib/orm_adapter/adapters/mongoid.rb#4
module Mongoid::Document
  include GeneratedInstanceMethods
  include ::ActiveSupport::Callbacks
  include ::ActiveModel::Validations::HelperMethods
  include ::ActiveModel::Validations
  include ::ActiveModel::Conversion
  include ::ActiveModel::API
  include ::ActiveModel::Model
  include ::ActiveModel::Serializers::JSON
  include ::Mongoid::Atomic
  include ::Mongoid::Changeable
  include ::Mongoid::Clients::StorageOptions
  include ::Mongoid::Clients::Options
  include ::Mongoid::Clients
  include ::Mongoid::CollectionConfigurable
  include ::Mongoid::Attributes::Nested
  include ::Mongoid::Attributes::Readonly
  include ::Mongoid::Attributes
  include ::Mongoid::Fields
  include ::Mongoid::Identifiable
  include ::Mongoid::Indexable
  include ::Mongoid::Matchable
  include ::Mongoid::Persistable::Creatable
  include ::Mongoid::Persistable::Deletable
  include ::Mongoid::Persistable::Destroyable
  include ::Mongoid::Persistable::Incrementable
  include ::Mongoid::Persistable::Logical
  include ::Mongoid::Persistable::Maxable
  include ::Mongoid::Persistable::Minable
  include ::Mongoid::Persistable::Multipliable
  include ::Mongoid::Persistable::Poppable
  include ::Mongoid::Persistable::Pullable
  include ::Mongoid::Persistable::Pushable
  include ::Mongoid::Persistable::Renamable
  include ::Mongoid::Persistable::Settable
  include ::Mongoid::Persistable::Unsettable
  include ::Mongoid::Persistable
  include ::Mongoid::Association::Embedded::Cyclic
  include ::Mongoid::Association::Referenced::AutoSave
  include ::Mongoid::Association::Referenced::CounterCache
  include ::Mongoid::Association::Accessors
  include ::Mongoid::Association::Depending
  include ::Mongoid::Association::Builders
  include ::Mongoid::Association::Macros
  include ::Mongoid::Association::Reflections
  include ::Mongoid::Association
  include ::Mongoid::Scopable
  include ::Mongoid::SearchIndexable
  include ::Mongoid::Selectable
  include ::Mongoid::Serializable
  include ::Mongoid::Shardable
  include ::Mongoid::Cacheable
  include ::Mongoid::Threaded::Lifecycle
  include ::Mongoid::Traversable
  include ::Mongoid::Validatable::Macros
  include ::Mongoid::Validatable
  include ::ActiveModel::Validations::Callbacks
  include ::Mongoid::Interceptable
  include ::Mongoid::Copyable
  include ::Mongoid::Equality
  include ::Mongoid::Encryptable
  include ::Mongoid::Composable

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveModel::Validations::ClassMethods
  mixes_in_class_methods ::ActiveModel::Callbacks
  mixes_in_class_methods ::ActiveSupport::Callbacks::ClassMethods
  mixes_in_class_methods ::ActiveSupport::DescendantsTracker
  mixes_in_class_methods ::ActiveModel::Translation
  mixes_in_class_methods ::ActiveModel::Validations::HelperMethods
  mixes_in_class_methods ::ActiveModel::Conversion::ClassMethods
  mixes_in_class_methods ::Mongoid::Changeable::ClassMethods
  mixes_in_class_methods ::Mongoid::Clients::StorageOptions::ClassMethods
  mixes_in_class_methods ::Mongoid::Clients::Options::ClassMethods
  mixes_in_class_methods ::Mongoid::Clients::Sessions::ClassMethods
  mixes_in_class_methods ::Mongoid::CollectionConfigurable::ClassMethods
  mixes_in_class_methods ::Mongoid::Attributes::Nested::ClassMethods
  mixes_in_class_methods ::Mongoid::Attributes::Readonly::ClassMethods
  mixes_in_class_methods ::Mongoid::Attributes::ClassMethods
  mixes_in_class_methods ::Mongoid::Fields::ClassMethods
  mixes_in_class_methods ::Mongoid::Identifiable::ClassMethods
  mixes_in_class_methods ::Mongoid::Indexable::ClassMethods
  mixes_in_class_methods ::Mongoid::Persistable::Creatable::ClassMethods
  mixes_in_class_methods ::Mongoid::Persistable::Deletable::ClassMethods
  mixes_in_class_methods ::Mongoid::Persistable::Destroyable::ClassMethods
  mixes_in_class_methods ::Mongoid::Association::Embedded::Cyclic::ClassMethods
  mixes_in_class_methods ::Mongoid::Association::Referenced::CounterCache::ClassMethods
  mixes_in_class_methods ::Mongoid::Association::Depending::ClassMethods
  mixes_in_class_methods ::Mongoid::Association::Macros::ClassMethods
  mixes_in_class_methods ::Mongoid::Association::Reflections::ClassMethods
  mixes_in_class_methods ::Mongoid::Association::Referenced::Syncable::ClassMethods
  mixes_in_class_methods ::Mongoid::Scopable::ClassMethods
  mixes_in_class_methods ::Mongoid::SearchIndexable::ClassMethods
  mixes_in_class_methods ::Mongoid::Shardable::ClassMethods
  mixes_in_class_methods ::Mongoid::Threaded::Lifecycle::ClassMethods
  mixes_in_class_methods ::Mongoid::Traversable::ClassMethods
  mixes_in_class_methods ::Mongoid::Traversable::DiscriminatorRetrieval
  mixes_in_class_methods ::Mongoid::Validatable::ClassMethods
  mixes_in_class_methods ::Mongoid::Validatable::Macros
  mixes_in_class_methods ::ActiveModel::Validations::Callbacks::ClassMethods
  mixes_in_class_methods ::Mongoid::Equality::ClassMethods
  mixes_in_class_methods ::Mongoid::Encryptable::ClassMethods
  mixes_in_class_methods ::Mongoid::Findable
  mixes_in_class_methods ::Mongoid::Document::ClassMethods
  mixes_in_class_methods ::Mongoid::Traversable::DiscriminatorAssignment

  module GeneratedClassMethods
    def __callbacks; end
    def __callbacks=(value); end
    def _declared_scopes; end
    def _declared_scopes=(value); end
    def _declared_scopes?; end
    def _validators; end
    def _validators=(value); end
    def _validators?; end
    def aliased_associations; end
    def aliased_associations=(value); end
    def aliased_associations?; end
    def aliased_fields; end
    def aliased_fields=(value); end
    def aliased_fields?; end
    def cyclic; end
    def cyclic=(value); end
    def cyclic?; end
    def default_scoping; end
    def default_scoping=(value); end
    def default_scoping?; end
    def dependents; end
    def dependents=(value); end
    def dependents?; end
    def dependents_owner; end
    def dependents_owner=(value); end
    def dependents_owner?; end
    def discriminator_key; end
    def discriminator_key=(value); end
    def discriminator_key?; end
    def embedded; end
    def embedded=(value); end
    def embedded?; end
    def embedded_relations; end
    def embedded_relations=(value); end
    def embedded_relations?; end
    def encrypt_metadata; end
    def encrypt_metadata=(value); end
    def encrypt_metadata?; end
    def fields; end
    def fields=(value); end
    def fields?; end
    def include_root_in_json; end
    def include_root_in_json=(value); end
    def include_root_in_json?; end
    def localized_fields; end
    def localized_fields=(value); end
    def localized_fields?; end
    def nested_attributes; end
    def nested_attributes=(value); end
    def nested_attributes?; end
    def param_delimiter; end
    def param_delimiter=(value); end
    def param_delimiter?; end
    def polymorphic; end
    def polymorphic=(value); end
    def polymorphic?; end
    def post_processed_defaults; end
    def post_processed_defaults=(value); end
    def post_processed_defaults?; end
    def pre_processed_defaults; end
    def pre_processed_defaults=(value); end
    def pre_processed_defaults?; end
    def readonly_attributes; end
    def readonly_attributes=(value); end
    def readonly_attributes?; end
    def relations; end
    def relations=(value); end
    def relations?; end
    def storage_options; end
    def storage_options=(value); end
    def storage_options?; end
    def stored_as_associations; end
    def stored_as_associations=(value); end
    def stored_as_associations?; end
  end

  module GeneratedInstanceMethods
    def __callbacks; end
    def _declared_scopes; end
    def _declared_scopes=(value); end
    def _declared_scopes?; end
    def _validators; end
    def _validators?; end
    def aliased_associations; end
    def aliased_associations=(value); end
    def aliased_associations?; end
    def aliased_fields; end
    def aliased_fields=(value); end
    def aliased_fields?; end
    def cyclic; end
    def cyclic=(value); end
    def cyclic?; end
    def default_scoping; end
    def default_scoping=(value); end
    def default_scoping?; end
    def dependents; end
    def dependents=(value); end
    def dependents?; end
    def dependents_owner; end
    def dependents_owner=(value); end
    def dependents_owner?; end
    def embedded=(value); end
    def embedded_relations; end
    def embedded_relations=(value); end
    def embedded_relations?; end
    def encrypt_metadata; end
    def encrypt_metadata=(value); end
    def encrypt_metadata?; end
    def fields; end
    def fields=(value); end
    def fields?; end
    def include_root_in_json; end
    def include_root_in_json?; end
    def localized_fields; end
    def localized_fields=(value); end
    def localized_fields?; end
    def nested_attributes; end
    def nested_attributes=(value); end
    def nested_attributes?; end
    def param_delimiter=(value); end
    def polymorphic; end
    def polymorphic=(value); end
    def polymorphic?; end
    def post_processed_defaults; end
    def post_processed_defaults=(value); end
    def post_processed_defaults?; end
    def pre_processed_defaults; end
    def pre_processed_defaults=(value); end
    def pre_processed_defaults?; end
    def readonly_attributes; end
    def readonly_attributes=(value); end
    def readonly_attributes?; end
    def relations; end
    def relations=(value); end
    def relations?; end
    def stored_as_associations; end
    def stored_as_associations=(value); end
    def stored_as_associations?; end
  end
end

# source://orm_adapter//lib/orm_adapter/adapters/mongoid.rb#5
module Mongoid::Document::ClassMethods
  include ::OrmAdapter::ToAdapter
end

# source://orm_adapter//lib/orm_adapter/adapters/mongoid.rb#9
class Mongoid::Document::OrmAdapter < ::OrmAdapter::Base
  # get a list of column names for a given class
  #
  # source://orm_adapter//lib/orm_adapter/adapters/mongoid.rb#11
  def column_names; end

  # @see OrmAdapter::Base#create!
  #
  # source://orm_adapter//lib/orm_adapter/adapters/mongoid.rb#38
  def create!(attributes = T.unsafe(nil)); end

  # @see OrmAdapter::Base#destroy
  #
  # source://orm_adapter//lib/orm_adapter/adapters/mongoid.rb#43
  def destroy(object); end

  # @see OrmAdapter::Base#find_all
  #
  # source://orm_adapter//lib/orm_adapter/adapters/mongoid.rb#32
  def find_all(options = T.unsafe(nil)); end

  # @see OrmAdapter::Base#find_first
  #
  # source://orm_adapter//lib/orm_adapter/adapters/mongoid.rb#26
  def find_first(options = T.unsafe(nil)); end

  # @see OrmAdapter::Base#get
  #
  # source://orm_adapter//lib/orm_adapter/adapters/mongoid.rb#21
  def get(id); end

  # @see OrmAdapter::Base#get!
  #
  # source://orm_adapter//lib/orm_adapter/adapters/mongoid.rb#16
  def get!(id); end

  protected

  # converts and documents to ids
  #
  # source://orm_adapter//lib/orm_adapter/adapters/mongoid.rb#50
  def conditions_to_fields(conditions); end
end

# source://orm_adapter//lib/orm_adapter/base.rb#1
module OrmAdapter
  class << self
    # A collection of registered adapters
    #
    # source://orm_adapter//lib/orm_adapter.rb#7
    def adapters; end
  end
end

# source://orm_adapter//lib/orm_adapter/base.rb#2
class OrmAdapter::Base
  # @return [Base] a new instance of Base
  #
  # source://orm_adapter//lib/orm_adapter/base.rb#17
  def initialize(klass); end

  # Get a list of column/property/field names
  #
  # @raise [NotSupportedError]
  #
  # source://orm_adapter//lib/orm_adapter/base.rb#22
  def column_names; end

  # Create a model using attributes
  #
  # @raise [NotSupportedError]
  #
  # source://orm_adapter//lib/orm_adapter/base.rb#72
  def create!(attributes = T.unsafe(nil)); end

  # Destroy an instance by passing in the instance itself.
  #
  # @raise [NotSupportedError]
  #
  # source://orm_adapter//lib/orm_adapter/base.rb#77
  def destroy(object); end

  # Find all models, optionally matching conditions, and specifying order
  #
  # @raise [NotSupportedError]
  # @see OrmAdapter::Base#find_first for how to specify order and conditions
  #
  # source://orm_adapter//lib/orm_adapter/base.rb#67
  def find_all(options = T.unsafe(nil)); end

  # Find the first instance, optionally matching conditions, and specifying order
  #
  # You can call with just conditions, providing a hash
  #
  #   User.to_adapter.find_first :name => "Fred", :age => 23
  #
  # Or you can specify :order, and :conditions as keys
  #
  #   User.to_adapter.find_first :conditions => {:name => "Fred", :age => 23}
  #   User.to_adapter.find_first :order => [:age, :desc]
  #   User.to_adapter.find_first :order => :name, :conditions => {:age => 18}
  #
  # When specifying :order, it may be
  # * a single arg e.g. <tt>:order => :name</tt>
  # * a single pair with :asc, or :desc as last, e.g. <tt>:order => [:name, :desc]</tt>
  # * an array of single args or pairs (with :asc or :desc as last), e.g. <tt>:order => [[:name, :asc], [:age, :desc]]</tt>
  #
  # @raise [NotSupportedError]
  #
  # source://orm_adapter//lib/orm_adapter/base.rb#61
  def find_first(options = T.unsafe(nil)); end

  # Get an instance by id of the model. Returns nil if a model is not found.
  # This should comply with ActiveModel#to_key API, i.e.:
  #
  #   User.to_adapter.get(@user.to_key) == @user
  #
  # @raise [NotSupportedError]
  #
  # source://orm_adapter//lib/orm_adapter/base.rb#40
  def get(id); end

  # Get an instance by id of the model. Raises an error if a model is not found.
  # This should comply with ActiveModel#to_key API, i.e.:
  #
  #   User.to_adapter.get!(@user.to_key) == @user
  #
  # @raise [NotSupportedError]
  #
  # source://orm_adapter//lib/orm_adapter/base.rb#31
  def get!(id); end

  # Returns the value of attribute klass.
  #
  # source://orm_adapter//lib/orm_adapter/base.rb#3
  def klass; end

  protected

  # given an options hash,
  # with optional :conditions, :order, :limit and :offset keys,
  # returns conditions, normalized order, limit and offset
  #
  # source://orm_adapter//lib/orm_adapter/base.rb#94
  def extract_conditions!(options = T.unsafe(nil)); end

  # given an order argument, returns an array of pairs, with each pair containing the attribute, and :asc or :desc
  #
  # source://orm_adapter//lib/orm_adapter/base.rb#104
  def normalize_order(order); end

  # @return [Boolean]
  #
  # source://orm_adapter//lib/orm_adapter/base.rb#83
  def valid_object?(object); end

  # source://orm_adapter//lib/orm_adapter/base.rb#87
  def wrap_key(key); end

  class << self
    # Your ORM adapter needs to inherit from this Base class and its adapter
    # will be registered. To create an adapter you should create an inner
    # constant "OrmAdapter" e.g. ActiveRecord::Base::OrmAdapter
    #
    # @see orm_adapters/active_record
    # @see orm_adapters/datamapper
    # @see orm_adapters/mongoid
    #
    # source://orm_adapter//lib/orm_adapter/base.rb#12
    def inherited(adapter); end
  end
end

# source://orm_adapter//lib/orm_adapter/base.rb#122
class OrmAdapter::NotSupportedError < ::NotImplementedError
  # source://orm_adapter//lib/orm_adapter/base.rb#123
  def to_s; end
end

# Extend into a class that has an OrmAdapter
#
# source://orm_adapter//lib/orm_adapter/to_adapter.rb#3
module OrmAdapter::ToAdapter
  # source://orm_adapter//lib/orm_adapter/to_adapter.rb#4
  def to_adapter; end
end

# source://orm_adapter//lib/orm_adapter/version.rb#2
OrmAdapter::VERSION = T.let(T.unsafe(nil), String)
