# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `persistent_httparty` gem.
# Please instead update this file by running `bin/tapioca gem persistent_httparty`.


module HTTParty::ClassMethods
  include ::HTTParty::Persistent::ClassMethods
end

# pkg:gem/persistent_httparty#lib/httparty/persistent.rb:3
module HTTParty::Persistent; end

# pkg:gem/persistent_httparty#lib/httparty/persistent.rb:4
module HTTParty::Persistent::ClassMethods
  # pkg:gem/persistent_httparty#lib/httparty/persistent.rb:5
  def persistent_connection_adapter(opts = T.unsafe(nil)); end
end

# pkg:gem/persistent_httparty#lib/httparty/persistent/connection_adapter.rb:4
class HTTParty::Persistent::ConnectionAdapter
  # pkg:gem/persistent_httparty#lib/httparty/persistent/connection_adapter.rb:15
  def build_persistent_http(uri, options); end

  # pkg:gem/persistent_httparty#lib/httparty/persistent/connection_adapter.rb:8
  def call(uri, options); end

  # Returns the value of attribute persistent_http.
  #
  # pkg:gem/persistent_httparty#lib/httparty/persistent/connection_adapter.rb:6
  def persistent_http; end

  # Sets the attribute persistent_http
  #
  # @param value the value to set the attribute persistent_http to.
  #
  # pkg:gem/persistent_httparty#lib/httparty/persistent/connection_adapter.rb:6
  def persistent_http=(_arg0); end
end

# pkg:gem/persistent_httparty#lib/persistent_httparty/version.rb:1
module PersistentHttparty; end

# pkg:gem/persistent_httparty#lib/persistent_httparty/version.rb:2
PersistentHttparty::VERSION = T.let(T.unsafe(nil), String)
