# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rack-proxy` gem.
# Please instead update this file by running `bin/tapioca gem rack-proxy`.


# pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:6
module Rack; end

# A lazy Rack body that streams a backend Net::HTTP response without
# buffering it.
#
# The request runs inside a Fiber, using only the public block form of
# Net::HTTP#request: the Fiber pauses (`Fiber.yield res`) the moment the
# status and headers are available, and #each resumes it to pull body chunks
# as the server consumes them. This replaced the 2010-era monkey-patch of
# private net/http internals (`net_http_hacked.rb`, deleted in 1.0) and
# inherits upstream's handling of 1xx interim responses, keep-alive
# negotiation, and transport errors.
#
# A Fiber can only be resumed from the thread that created it. The request
# Fiber is created lazily on first use (#code/#headers/#each), so the normal
# Rack flow — one thread calls the app and then iterates the body — is fine.
# If #close is called from a different thread (some servers do this on client
# abort), the Fiber unwind is skipped and the connection is hard-closed
# instead, which releases the socket either way.
#
# pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:24
class Rack::HttpStreamingResponse
  # An optional block receives the Net::HTTP instance for configuration before
  # it connects — this is the single source of truth used by Rack::Proxy (see
  # Rack::Proxy#configure_backend_connection). When no block is given, the
  # public accessors above are applied instead (backward-compatible path for
  # direct users of this class).
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:50
  def initialize(request, host, port = T.unsafe(nil), &configure); end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:63
  def body; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def cert; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def cert=(_arg0); end

  # Rack calls #close on the response body when it is done with it, including
  # when it bails out early (HEAD, 304, a client disconnect). Without this, a
  # body that is never iterated leaks the backend TCP/TLS connection until GC.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:116
  def close; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:67
  def code; end

  # Can be called only once!
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:80
  def each(&block); end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:75
  def headers; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def key; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def key=(_arg0); end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def logger; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def logger=(_arg0); end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:43
  def max_response_length; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:43
  def max_response_length=(_arg0); end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def read_timeout; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def read_timeout=(_arg0); end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def ssl_version; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def ssl_version=(_arg0); end

  # #status is deprecated
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:73
  def status; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:109
  def to_s; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def use_ssl; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def use_ssl=(_arg0); end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def verify_mode; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:42
  def verify_mode=(_arg0); end

  protected

  # Net::HTTPResponse. Fetching it lazily dials the backend, sends the request
  # and reads the response head; the body stays unread on the socket until
  # #each resumes the Fiber.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:125
  def response; end

  # Net::HTTP
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:147
  def session; end

  private

  # Idempotent, best-effort teardown. Uses @session/@fiber directly (never the
  # lazy accessors) so closing a response that was never read does not dial
  # the backend just to tear it down. A still-suspended request Fiber is
  # unwound first (running net/http's own ensure blocks), then the connection
  # is closed for real. Swallows teardown errors: a half-read or already-reset
  # backend must not crash the app or mask the original error.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:181
  def close_connection; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:173
  def connection_closed; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:173
  def connection_closed=(_arg0); end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:171
  def host; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:171
  def port; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:171
  def request; end
end

# Raised while streaming when the backend body exceeds max_response_length.
# The status/headers are already sent, so the transfer is aborted mid-stream.
#
# pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:27
class Rack::HttpStreamingResponse::ResponseTooLarge < ::StandardError; end

# pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:36
Rack::HttpStreamingResponse::STATUSES_WITH_NO_ENTITY_BODY = T.let(T.unsafe(nil), Hash)

# Raised INTO the request Fiber to unwind it on early termination (client
# abort, HEAD, 204/304, oversize response). Deliberately a direct
# StandardError subclass — it must never match the network-error classes
# Net::HTTP#request retries on, or aborting a stream could replay the
# request against the backend.
#
# pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:34
class Rack::HttpStreamingResponse::StreamAborted < ::StandardError; end

# Subclass and bring your own #rewrite_request and #rewrite_response
#
# pkg:gem/rack-proxy#lib/rack/proxy/version.rb:4
class Rack::Proxy
  # @option opts [String, URI::HTTP] :backend Backend host to proxy requests to
  #
  # pkg:gem/rack-proxy#lib/rack/proxy.rb:95
  def initialize(app = T.unsafe(nil), opts = T.unsafe(nil)); end

  # SSRF guardrail, consulted for EVERY request with the resolved backend
  # (`backend` responds to #host, #port and #scheme). Return false to refuse,
  # which makes the proxy respond 502. The default allows the backend, because
  # by the time this hook runs the destination is either app-configured
  # (:backend / env["rack.backend"]) or the deployment has explicitly passed
  # allow_dynamic_backend: true — override it to pin an allowlist on top:
  #
  #   def backend_allowed?(backend)
  #     %w[api.internal.example.com].include?(backend.host)
  #   end
  #
  # pkg:gem/rack-proxy#lib/rack/proxy.rb:180
  def backend_allowed?(backend); end

  # pkg:gem/rack-proxy#lib/rack/proxy.rb:156
  def call(env); end

  # Return modified env
  #
  # pkg:gem/rack-proxy#lib/rack/proxy.rb:161
  def rewrite_env(env); end

  # Return a rack triplet [status, headers, body]
  #
  # pkg:gem/rack-proxy#lib/rack/proxy.rb:166
  def rewrite_response(triplet); end

  protected

  # pkg:gem/rack-proxy#lib/rack/proxy.rb:186
  def perform_request(env); end

  private

  # Single source of truth for TLS/timeout setup, applied to the (real
  # Net::HTTP) connection on both the streaming and non-streaming paths so a
  # TLS option — notably the VERIFY_PEER default — can never land on only one.
  #
  # pkg:gem/rack-proxy#lib/rack/proxy.rb:341
  def configure_backend_connection(conn, use_ssl:, read_timeout:); end

  # Resolve the Net::HTTP request class for an HTTP method, or nil if there is
  # no matching Net::HTTP::<Verb> (unknown/unsupported method -> 501).
  #
  # pkg:gem/rack-proxy#lib/rack/proxy.rb:332
  def net_http_request_class(method); end

  # Enforce :max_response_length. Returns true (→ 502) when the response is
  # already known to be too large. For streaming, a declared oversize is
  # rejected up-front (the connection is closed) and the incremental limit is
  # armed on the body for chunked/unknown-length responses; for non-streaming,
  # the body is already buffered so we check its actual size. Returns false
  # (allow) when no cap is set.
  #
  # pkg:gem/rack-proxy#lib/rack/proxy.rb:311
  def response_too_large?(target_response, headers, body); end

  class << self
    # pkg:gem/rack-proxy#lib/rack/proxy.rb:71
    def build_header_hash(pairs); end

    # pkg:gem/rack-proxy#lib/rack/proxy.rb:41
    def extract_http_request_headers(env); end

    # pkg:gem/rack-proxy#lib/rack/proxy.rb:64
    def normalize_headers(headers); end

    protected

    # pkg:gem/rack-proxy#lib/rack/proxy.rb:85
    def reconstruct_header_name(name); end

    # pkg:gem/rack-proxy#lib/rack/proxy.rb:89
    def titleize(str); end
  end
end

# Backend/network failures that must surface as 502 Bad Gateway rather than
# crashing the proxy with a raw 500. Construction- and policy-time failures
# are mapped separately (400/501/502) in #perform_request.
#
# pkg:gem/rack-proxy#lib/rack/proxy.rb:25
Rack::Proxy::BACKEND_ERRORS = T.let(T.unsafe(nil), Array)

# pkg:gem/rack-proxy#lib/rack/proxy.rb:11
Rack::Proxy::HOP_BY_HOP_HEADERS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack-proxy#lib/rack/proxy/version.rb:5
Rack::Proxy::VERSION = T.let(T.unsafe(nil), String)
