# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rack-proxy` gem.
# Please instead update this file by running `bin/tapioca gem rack-proxy`.


# pkg:gem/rack-proxy#lib/net_http_hacked.rb:19
class Net::HTTP < ::Net::Protocol
  # Original #request with block semantics.
  #
  # def request(req, body = nil, &block)
  #   unless started?
  #     start {
  #       req['connection'] ||= 'close'
  #       return request(req, body, &block)
  #     }
  #   end
  #   if proxy_user()
  #     unless use_ssl?
  #       req.proxy_basic_auth proxy_user(), proxy_pass()
  #     end
  #   end
  #
  #   req.set_body_internal body
  #   begin_transport req
  #     req.exec @socket, @curr_http_version, edit_path(req.path)
  #     begin
  #       res = HTTPResponse.read_new(@socket)
  #     end while res.kind_of?(HTTPContinue)
  #     res.reading_body(@socket, req.response_body_permitted?) {
  #       yield res if block_given?
  #     }
  #   end_transport req, res
  #
  #   res
  # end
  #
  # pkg:gem/rack-proxy#lib/net_http_hacked.rb:49
  def begin_request_hacked(req); end

  # pkg:gem/rack-proxy#lib/net_http_hacked.rb:60
  def end_request_hacked; end
end

# pkg:gem/rack-proxy#lib/net_http_hacked.rb:67
class Net::HTTPResponse
  # Original #reading_body with block semantics
  #
  #   @socket = sock
  #   @body_exist = reqmethodallowbody && self.class.body_permitted?
  #   begin
  #     yield
  #     self.body   # ensure to read body
  #   ensure
  #     @socket = nil
  #   end
  # end
  #
  # pkg:gem/rack-proxy#lib/net_http_hacked.rb:81
  def begin_reading_body_hacked(sock, reqmethodallowbody); end

  # pkg:gem/rack-proxy#lib/net_http_hacked.rb:86
  def end_reading_body_hacked; end
end

# pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:4
module Rack; end

# Wraps the hacked net/http in a Rack way.
#
# pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:6
class Rack::HttpStreamingResponse
  # @return [HttpStreamingResponse] a new instance of HttpStreamingResponse
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:15
  def initialize(request, host, port = T.unsafe(nil)); end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:19
  def body; end

  # Returns the value of attribute cert.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:13
  def cert; end

  # Sets the attribute cert
  #
  # @param value the value to set the attribute cert to.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:13
  def cert=(_arg0); end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:23
  def code; end

  # Can be called only once!
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:36
  def each(&block); end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:31
  def headers; end

  # Returns the value of attribute key.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:13
  def key; end

  # Sets the attribute key
  #
  # @param value the value to set the attribute key to.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:13
  def key=(_arg0); end

  # Returns the value of attribute read_timeout.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:13
  def read_timeout; end

  # Sets the attribute read_timeout
  #
  # @param value the value to set the attribute read_timeout to.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:13
  def read_timeout=(_arg0); end

  # Returns the value of attribute ssl_version.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:13
  def ssl_version; end

  # Sets the attribute ssl_version
  #
  # @param value the value to set the attribute ssl_version to.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:13
  def ssl_version=(_arg0); end

  # #status is deprecated
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:29
  def status; end

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:44
  def to_s; end

  # Returns the value of attribute use_ssl.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:13
  def use_ssl; end

  # Sets the attribute use_ssl
  #
  # @param value the value to set the attribute use_ssl to.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:13
  def use_ssl=(_arg0); end

  # Returns the value of attribute verify_mode.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:13
  def verify_mode; end

  # Sets the attribute verify_mode
  #
  # @param value the value to set the attribute verify_mode to.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:13
  def verify_mode=(_arg0); end

  protected

  # Net::HTTPResponse
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:51
  def response; end

  # Net::HTTP
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:56
  def session; end

  private

  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:74
  def close_connection; end

  # Returns the value of attribute connection_closed.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:72
  def connection_closed; end

  # Sets the attribute connection_closed
  #
  # @param value the value to set the attribute connection_closed to.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:72
  def connection_closed=(_arg0); end

  # Returns the value of attribute host.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:70
  def host; end

  # Returns the value of attribute port.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:70
  def port; end

  # Returns the value of attribute request.
  #
  # pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:70
  def request; end
end

# pkg:gem/rack-proxy#lib/rack/http_streaming_response.rb:7
Rack::HttpStreamingResponse::STATUSES_WITH_NO_ENTITY_BODY = T.let(T.unsafe(nil), Hash)

# Subclass and bring your own #rewrite_request and #rewrite_response
#
# pkg:gem/rack-proxy#lib/rack/proxy.rb:7
class Rack::Proxy
  # @option opts
  # @param opts [Hash] a customizable set of options
  # @return [Proxy] a new instance of Proxy
  #
  # pkg:gem/rack-proxy#lib/rack/proxy.rb:63
  def initialize(app = T.unsafe(nil), opts = T.unsafe(nil)); end

  # pkg:gem/rack-proxy#lib/rack/proxy.rb:86
  def call(env); end

  # Return modified env
  #
  # pkg:gem/rack-proxy#lib/rack/proxy.rb:91
  def rewrite_env(env); end

  # Return a rack triplet [status, headers, body]
  #
  # pkg:gem/rack-proxy#lib/rack/proxy.rb:96
  def rewrite_response(triplet); end

  protected

  # pkg:gem/rack-proxy#lib/rack/proxy.rb:102
  def perform_request(env); end

  class << self
    # pkg:gem/rack-proxy#lib/rack/proxy.rb:41
    def build_header_hash(pairs); end

    # pkg:gem/rack-proxy#lib/rack/proxy.rb:22
    def extract_http_request_headers(env); end

    # pkg:gem/rack-proxy#lib/rack/proxy.rb:34
    def normalize_headers(headers); end

    protected

    # pkg:gem/rack-proxy#lib/rack/proxy.rb:53
    def reconstruct_header_name(name); end

    # pkg:gem/rack-proxy#lib/rack/proxy.rb:57
    def titleize(str); end
  end
end

# pkg:gem/rack-proxy#lib/rack/proxy.rb:10
Rack::Proxy::HOP_BY_HOP_HEADERS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack-proxy#lib/rack/proxy.rb:8
Rack::Proxy::VERSION = T.let(T.unsafe(nil), String)
