# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `turbo-rails` gem.
# Please instead update this file by running `bin/tapioca gem turbo-rails`.

# source://turbo-rails//lib/turbo/engine.rb#3
module Turbo
  extend ::ActiveSupport::Autoload

  # source://activesupport/7.1.3/lib/active_support/core_ext/module/attribute_accessors_per_thread.rb#74
  def current_request_id; end

  # source://activesupport/7.1.3/lib/active_support/core_ext/module/attribute_accessors_per_thread.rb#116
  def current_request_id=(obj); end

  # source://turbo-rails//lib/turbo-rails.rb#7
  def draw_routes; end

  # source://turbo-rails//lib/turbo-rails.rb#7
  def draw_routes=(val); end

  class << self
    # source://activesupport/7.1.3/lib/active_support/core_ext/module/attribute_accessors_per_thread.rb#49
    def current_request_id; end

    # source://activesupport/7.1.3/lib/active_support/core_ext/module/attribute_accessors_per_thread.rb#108
    def current_request_id=(obj); end

    # source://turbo-rails//lib/turbo-rails.rb#7
    def draw_routes; end

    # source://turbo-rails//lib/turbo-rails.rb#7
    def draw_routes=(val); end

    # source://railties/7.1.3/lib/rails/engine.rb#412
    def railtie_helpers_paths; end

    # source://railties/7.1.3/lib/rails/engine.rb#395
    def railtie_namespace; end

    # source://railties/7.1.3/lib/rails/engine.rb#416
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # source://turbo-rails//lib/turbo-rails.rb#14
    def signed_stream_verifier; end

    # source://turbo-rails//lib/turbo-rails.rb#18
    def signed_stream_verifier_key; end

    # Sets the attribute signed_stream_verifier_key
    #
    # @param value the value to set the attribute signed_stream_verifier_key to.
    #
    # source://turbo-rails//lib/turbo-rails.rb#12
    def signed_stream_verifier_key=(_arg0); end

    # source://railties/7.1.3/lib/rails/engine.rb#398
    def table_name_prefix; end

    # source://railties/7.1.3/lib/rails/engine.rb#408
    def use_relative_model_naming?; end

    # source://turbo-rails//lib/turbo-rails.rb#22
    def with_request_id(request_id); end
  end
end

# source://turbo-rails//lib/turbo/broadcastable/test_helper.rb#2
module Turbo::Broadcastable; end

# source://turbo-rails//lib/turbo/broadcastable/test_helper.rb#3
module Turbo::Broadcastable::TestHelper
  extend ::ActiveSupport::Concern
  include ::ActionCable::TestHelper
  include ::Turbo::Streams::StreamName

  # Asserts that no `<turbo-stream>` elements were broadcast over Action Cable
  #
  # === Arguments
  #
  # * <tt>stream_name_or_object</tt> the objects used to generate the
  #   channel Action Cable name, or the name itself
  # * <tt>&block</tt> optional block executed before the
  #   assertion
  #
  # Asserts that no `<turbo-stream>` elements were broadcast:
  #
  #     message = Message.find(1)
  #     message.broadcast_replace_to "messages"
  #
  #     assert_no_turbo_stream_broadcasts "messages" # fails with MiniTest::Assertion error
  #
  # You can pass a block to run before the assertion:
  #
  #     message = Message.find(1)
  #
  #     assert_no_turbo_stream_broadcasts "messages" do
  #       # do something other than broadcast to "messages"
  #     end
  #
  # In addition to a String, the helper also accepts an Object or Array to
  # determine the name of the channel the elements are broadcast to:
  #
  #     message = Message.find(1)
  #
  #     assert_no_turbo_stream_broadcasts message do
  #       # do something other than broadcast to "message_1"
  #     end
  #
  # source://turbo-rails//lib/turbo/broadcastable/test_helper.rb#104
  def assert_no_turbo_stream_broadcasts(stream_name_or_object, &block); end

  # Asserts that `<turbo-stream>` elements were broadcast over Action Cable
  #
  # === Arguments
  #
  # * <tt>stream_name_or_object</tt> the objects used to generate the
  #   channel Action Cable name, or the name itself
  # * <tt>&block</tt> optional block executed before the
  #   assertion
  #
  # === Options
  #
  # * <tt>count:</tt> the number of `<turbo-stream>` elements that are
  # expected to be broadcast
  #
  # Asserts `<turbo-stream>` elements were broadcast:
  #
  #     message = Message.find(1)
  #     message.broadcast_replace_to "messages"
  #
  #     assert_turbo_stream_broadcasts "messages"
  #
  # Asserts that two `<turbo-stream>` elements were broadcast:
  #
  #     message = Message.find(1)
  #     message.broadcast_replace_to "messages"
  #     message.broadcast_remove_to "messages"
  #
  #     assert_turbo_stream_broadcasts "messages", count: 2
  #
  # You can pass a block to run before the assertion:
  #
  #     message = Message.find(1)
  #
  #     assert_turbo_stream_broadcasts "messages" do
  #       message.broadcast_append_to "messages"
  #     end
  #
  # In addition to a String, the helper also accepts an Object or Array to
  # determine the name of the channel the elements are broadcast to:
  #
  #     message = Message.find(1)
  #
  #     assert_turbo_stream_broadcasts message do
  #       message.broadcast_replace
  #     end
  #
  # source://turbo-rails//lib/turbo/broadcastable/test_helper.rb#58
  def assert_turbo_stream_broadcasts(stream_name_or_object, count: T.unsafe(nil), &block); end

  # Captures any `<turbo-stream>` elements that were broadcast over Action Cable
  #
  # === Arguments
  #
  # * <tt>stream_name_or_object</tt> the objects used to generate the
  #   channel Action Cable name, or the name itself
  # * <tt>&block</tt> optional block to capture broadcasts during execution
  #
  # Returns any `<turbo-stream>` elements that have been broadcast as an
  # Array of <tt>Nokogiri::XML::Element</tt> instances
  #
  #     message = Message.find(1)
  #     message.broadcast_append_to "messages"
  #     message.broadcast_prepend_to "messages"
  #
  #     turbo_streams = capture_turbo_stream_broadcasts "messages"
  #
  #     assert_equal "append", turbo_streams.first["action"]
  #     assert_equal "prepend", turbo_streams.second["action"]
  #
  # You can pass a block to limit the scope of the broadcasts being captured:
  #
  #     message = Message.find(1)
  #
  #     turbo_streams = capture_turbo_stream_broadcasts "messages" do
  #       message.broadcast_append_to "messages"
  #     end
  #
  #     assert_equal "append", turbo_streams.first["action"]
  #
  # In addition to a String, the helper also accepts an Object or Array to
  # determine the name of the channel the elements are broadcast to:
  #
  #     message = Message.find(1)
  #
  #     replace, remove = capture_turbo_stream_broadcasts message do
  #       message.broadcast_replace
  #       message.broadcast_remove
  #     end
  #
  #     assert_equal "replace", replace["action"]
  #     assert_equal "replace", remove["action"]
  #
  # source://turbo-rails//lib/turbo/broadcastable/test_helper.rb#157
  def capture_turbo_stream_broadcasts(stream_name_or_object, &block); end
end

class Turbo::Debouncer
  def initialize(delay: T.unsafe(nil)); end

  def debounce(&block); end
  def delay; end
  def scheduled_task; end
  def wait; end

  private

  def wait_timeout; end
end

Turbo::Debouncer::DEFAULT_DELAY = T.let(T.unsafe(nil), Float)

module Turbo::DriveHelper
  def turbo_exempts_page_from_cache; end
  def turbo_exempts_page_from_cache_tag; end
  def turbo_exempts_page_from_preview; end
  def turbo_exempts_page_from_preview_tag; end
  def turbo_page_requires_reload; end
  def turbo_page_requires_reload_tag; end
  def turbo_refresh_method_tag(method = T.unsafe(nil)); end
  def turbo_refresh_scroll_tag(scroll = T.unsafe(nil)); end
  def turbo_refreshes_with(method: T.unsafe(nil), scroll: T.unsafe(nil)); end
end

# source://turbo-rails//lib/turbo/engine.rb#4
class Turbo::Engine < ::Rails::Engine
  class << self
    # source://activesupport/7.1.3/lib/active_support/callbacks.rb#70
    def __callbacks; end
  end
end

# If you don't want to precompile Turbo's assets (eg. because you're using webpack),
# you can do this in an intiailzer:
#
# config.after_initialize do
#   config.assets.precompile -= Turbo::Engine::PRECOMPILE_ASSETS
# end
#
# source://turbo-rails//lib/turbo/engine.rb#28
Turbo::Engine::PRECOMPILE_ASSETS = T.let(T.unsafe(nil), Array)

module Turbo::Frames; end

module Turbo::Frames::FrameRequest
  extend ::ActiveSupport::Concern

  private

  def turbo_frame_request?; end
  def turbo_frame_request_id; end
end

module Turbo::FramesHelper
  def turbo_frame_tag(*ids, src: T.unsafe(nil), target: T.unsafe(nil), **attributes, &block); end
end

module Turbo::IncludesHelper
  def turbo_include_tags; end
end

module Turbo::Native; end

module Turbo::Native::Navigation
  extend ::ActiveSupport::Concern

  def recede_or_redirect_back_or_to(url, **options); end
  def recede_or_redirect_to(url, **options); end
  def refresh_or_redirect_back_or_to(url, **options); end
  def refresh_or_redirect_to(url, **options); end
  def resume_or_redirect_back_or_to(url, **options); end
  def resume_or_redirect_to(url, **options); end
  def turbo_native_app?; end

  private

  def turbo_native_action_or_redirect(url, action, redirect_type, options = T.unsafe(nil)); end
end

class Turbo::Native::NavigationController < ::ActionController::Base
  def recede; end
  def refresh; end
  def resume; end

  private

  # source://actionview/7.1.3/lib/action_view/layouts.rb#330
  def _layout(lookup_context, formats); end

  class << self
    # source://actionpack/7.1.3/lib/action_controller/metal.rb#262
    def middleware_stack; end
  end
end

module Turbo::RequestIdTracking
  extend ::ActiveSupport::Concern

  private

  def turbo_tracking_request_id(&block); end
end

module Turbo::Streams; end

class Turbo::Streams::ActionBroadcastJob < ::ActiveJob::Base
  def perform(stream, action:, target:, attributes: T.unsafe(nil), **rendering); end

  class << self
    # source://activesupport/7.1.3/lib/active_support/rescuable.rb#15
    def rescue_handlers; end
  end
end

module Turbo::Streams::ActionHelper
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper

  def turbo_stream_action_tag(action, target: T.unsafe(nil), targets: T.unsafe(nil), template: T.unsafe(nil), **attributes); end
  def turbo_stream_refresh_tag(request_id: T.unsafe(nil), **attributes); end

  private

  def convert_to_turbo_stream_dom_id(target, include_selector: T.unsafe(nil)); end
end

class Turbo::Streams::BroadcastJob < ::ActiveJob::Base
  def perform(stream, **rendering); end

  class << self
    # source://activesupport/7.1.3/lib/active_support/rescuable.rb#15
    def rescue_handlers; end
  end
end

class Turbo::Streams::BroadcastStreamJob < ::ActiveJob::Base
  def perform(stream, content:); end

  class << self
    # source://activesupport/7.1.3/lib/active_support/rescuable.rb#15
    def rescue_handlers; end
  end
end

module Turbo::Streams::Broadcasts
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::Turbo::Streams::ActionHelper

  def broadcast_action_later_to(*streamables, action:, target: T.unsafe(nil), targets: T.unsafe(nil), attributes: T.unsafe(nil), **rendering); end
  def broadcast_action_to(*streamables, action:, target: T.unsafe(nil), targets: T.unsafe(nil), attributes: T.unsafe(nil), **rendering); end
  def broadcast_after_later_to(*streamables, **opts); end
  def broadcast_after_to(*streamables, **opts); end
  def broadcast_append_later_to(*streamables, **opts); end
  def broadcast_append_to(*streamables, **opts); end
  def broadcast_before_later_to(*streamables, **opts); end
  def broadcast_before_to(*streamables, **opts); end
  def broadcast_prepend_later_to(*streamables, **opts); end
  def broadcast_prepend_to(*streamables, **opts); end
  def broadcast_refresh_later_to(*streamables, request_id: T.unsafe(nil), **opts); end
  def broadcast_refresh_to(*streamables, **opts); end
  def broadcast_remove_to(*streamables, **opts); end
  def broadcast_render_later_to(*streamables, **rendering); end
  def broadcast_render_to(*streamables, **rendering); end
  def broadcast_replace_later_to(*streamables, **opts); end
  def broadcast_replace_to(*streamables, **opts); end
  def broadcast_stream_to(*streamables, content:); end
  def broadcast_update_later_to(*streamables, **opts); end
  def broadcast_update_to(*streamables, **opts); end
  def refresh_debouncer_for(*streamables, request_id: T.unsafe(nil)); end

  private

  def render_format(format, **rendering); end
end

module Turbo::Streams::StreamName
  def signed_stream_name(streamables); end
  def verified_stream_name(signed_stream_name); end

  private

  def stream_name_from(streamables); end
end

module Turbo::Streams::StreamName::ClassMethods
  def verified_stream_name_from_params; end
end

class Turbo::Streams::TagBuilder
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::Turbo::Streams::ActionHelper

  def initialize(view_context); end

  def action(name, target, content = T.unsafe(nil), allow_inferred_rendering: T.unsafe(nil), **rendering, &block); end
  def action_all(name, targets, content = T.unsafe(nil), allow_inferred_rendering: T.unsafe(nil), **rendering, &block); end
  def after(target, content = T.unsafe(nil), **rendering, &block); end
  def after_all(targets, content = T.unsafe(nil), **rendering, &block); end
  def append(target, content = T.unsafe(nil), **rendering, &block); end
  def append_all(targets, content = T.unsafe(nil), **rendering, &block); end
  def before(target, content = T.unsafe(nil), **rendering, &block); end
  def before_all(targets, content = T.unsafe(nil), **rendering, &block); end
  def prepend(target, content = T.unsafe(nil), **rendering, &block); end
  def prepend_all(targets, content = T.unsafe(nil), **rendering, &block); end
  def remove(target); end
  def remove_all(targets); end
  def replace(target, content = T.unsafe(nil), **rendering, &block); end
  def replace_all(targets, content = T.unsafe(nil), **rendering, &block); end
  def update(target, content = T.unsafe(nil), **rendering, &block); end
  def update_all(targets, content = T.unsafe(nil), **rendering, &block); end

  private

  def render_record(possible_record); end
  def render_template(target, content = T.unsafe(nil), allow_inferred_rendering: T.unsafe(nil), **rendering, &block); end
end

module Turbo::Streams::TurboStreamsTagBuilder
  private

  def turbo_stream; end
end

class Turbo::StreamsChannel < ::ActionCable::Channel::Base
  include ::Turbo::Streams::StreamName::ClassMethods
  extend ::Turbo::Streams::StreamName
  extend ::ActionView::Helpers::CaptureHelper
  extend ::ActionView::Helpers::OutputSafetyHelper
  extend ::ActionView::Helpers::TagHelper
  extend ::Turbo::Streams::ActionHelper
  extend ::Turbo::Streams::Broadcasts

  def subscribed; end

  class << self
    # source://activesupport/7.1.3/lib/active_support/callbacks.rb#70
    def __callbacks; end
  end
end

module Turbo::StreamsHelper
  def turbo_stream; end
  def turbo_stream_from(*streamables, **attributes); end
end

# source://turbo-rails//lib/turbo/test_assertions.rb#2
module Turbo::TestAssertions
  extend ::ActiveSupport::Concern

  # Assert that the rendered fragment of HTML does not contain a `<turbo-stream>`
  # element.
  #
  # === Options
  #
  # * <tt>:action</tt> [String] matches the element's <tt>[action]</tt>
  #   attribute
  # * <tt>:target</tt> [String, #to_key] matches the element's
  #   <tt>[target]</tt> attribute. If the value responds to <tt>#to_key</tt>,
  #   the value will be transformed by calling <tt>dom_id</tt>
  # * <tt>:targets</tt> [String] matches the element's <tt>[targets]</tt>
  #   attribute
  #
  #   Given the following HTML fragment:
  #
  #     <turbo-stream action="remove" target="message_1"></turbo-stream>
  #
  #   The following assertion would fail:
  #
  #     assert_no_turbo_stream action: "remove", target: "message_1"
  #
  # source://turbo-rails//lib/turbo/test_assertions.rb#76
  def assert_no_turbo_stream(action:, target: T.unsafe(nil), targets: T.unsafe(nil)); end

  # Assert that the rendered fragment of HTML contains a `<turbo-stream>`
  # element.
  #
  # === Options
  #
  # * <tt>:action</tt> [String] matches the element's <tt>[action]</tt>
  #   attribute
  # * <tt>:target</tt> [String, #to_key] matches the element's
  #   <tt>[target]</tt> attribute. If the value responds to <tt>#to_key</tt>,
  #   the value will be transformed by calling <tt>dom_id</tt>
  # * <tt>:targets</tt> [String] matches the element's <tt>[targets]</tt>
  #   attribute
  # * <tt>:count</tt> [Integer] indicates how many turbo streams are expected.
  #   Defaults to <tt>1</tt>.
  #
  #   Given the following HTML fragment:
  #
  #     <turbo-stream action="remove" target="message_1"></turbo-stream>
  #
  #   The following assertion would pass:
  #
  #     assert_turbo_stream action: "remove", target: "message_1"
  #
  # You can also pass a block make assertions about the contents of the
  # element. Given the following HTML fragment:
  #
  #     <turbo-stream action="replace" target="message_1">
  #       <template>
  #         <p>Hello!</p>
  #       <template>
  #     </turbo-stream>
  #
  #   The following assertion would pass:
  #
  #     assert_turbo_stream action: "replace", target: "message_1" do
  #       assert_select "template p", text: "Hello!"
  #     end
  #
  # source://turbo-rails//lib/turbo/test_assertions.rb#48
  def assert_turbo_stream(action:, target: T.unsafe(nil), targets: T.unsafe(nil), count: T.unsafe(nil), &block); end
end

# source://turbo-rails//lib/turbo/test_assertions/integration_test_assertions.rb#3
module Turbo::TestAssertions::IntegrationTestAssertions
  # Assert that the Turbo Stream request's response body's HTML does not
  # contain a `<turbo-stream>` element.
  #
  # === Options
  #
  # * <tt>:status</tt> [Integer, Symbol] the HTTP response status
  # * <tt>:action</tt> [String] matches the element's <tt>[action]</tt>
  #   attribute
  # * <tt>:target</tt> [String, #to_key] matches the element's
  #   <tt>[target]</tt> attribute. If the value responds to <tt>#to_key</tt>,
  #   the value will be transformed by calling <tt>dom_id</tt>
  # * <tt>:targets</tt> [String] matches the element's <tt>[targets]</tt>
  #   attribute
  #
  #   Given the following HTML response body:
  #
  #     <turbo-stream action="remove" target="message_1"></turbo-stream>
  #
  #   The following assertion would fail:
  #
  #     assert_no_turbo_stream action: "remove", target: "message_1"
  #
  # source://turbo-rails//lib/turbo/test_assertions/integration_test_assertions.rb#69
  def assert_no_turbo_stream(status: T.unsafe(nil), **attributes); end

  # Assert that the Turbo Stream request's response body's HTML contains a
  # `<turbo-stream>` element.
  #
  # === Options
  #
  # * <tt>:status</tt> [Integer, Symbol] the HTTP response status
  # * <tt>:action</tt> [String] matches the element's <tt>[action]</tt>
  #   attribute
  # * <tt>:target</tt> [String, #to_key] matches the element's
  #   <tt>[target]</tt> attribute. If the value responds to <tt>#to_key</tt>,
  #   the value will be transformed by calling <tt>dom_id</tt>
  # * <tt>:targets</tt> [String] matches the element's <tt>[targets]</tt>
  #   attribute
  #
  #   Given the following HTML response body:
  #
  #     <turbo-stream action="remove" target="message_1"></turbo-stream>
  #
  #   The following assertion would pass:
  #
  #     assert_turbo_stream action: "remove", target: "message_1"
  #
  # You can also pass a block make assertions about the contents of the
  # element. Given the following HTML response body:
  #
  #     <turbo-stream action="replace" target="message_1">
  #       <template>
  #         <p>Hello!</p>
  #       <template>
  #     </turbo-stream>
  #
  #   The following assertion would pass:
  #
  #     assert_turbo_stream action: "replace", target: "message_1" do
  #       assert_select "template p", text: "Hello!"
  #     end
  #
  # source://turbo-rails//lib/turbo/test_assertions/integration_test_assertions.rb#41
  def assert_turbo_stream(status: T.unsafe(nil), **attributes, &block); end
end

class Turbo::ThreadDebouncer
  def initialize(key, thread, delay:); end

  def debounce; end
  def wait(*_arg0, **_arg1, &_arg2); end

  private

  def debouncer; end
  def key; end
  def thread; end

  class << self
    def for(key, delay: T.unsafe(nil)); end

    private

    def new(*_arg0); end
  end
end
