# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mongoid::Association::Depending`.
# Please instead update this file by running `bin/tapioca dsl Mongoid::Association::Depending`.


module Mongoid::Association::Depending
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods

  module GeneratedClassMethods
    def _dependents_owner; end
    def _dependents_owner=(value); end
    def _dependents_owner?; end
    def dependents; end
    def dependents=(value); end
    def dependents?; end
  end

  module GeneratedInstanceMethods
    def _dependents_owner; end
    def _dependents_owner=(value); end
    def _dependents_owner?; end
    def dependents; end
    def dependents=(value); end
    def dependents?; end
  end
end
