version: "3.9"

services:
  db:
    container_name: aldwin7894-mongo
    image: mongo:4.4
    restart: always
    environment:
      - TZ
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
  redis:
    container_name: aldwin7894-redis
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    environment:
      - TZ
    ports:
      - 6379:6379
    volumes:
      - redis:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - TZ
        - RAILS_ENV
        - NODE_ENV
        - OCCSON_ACCESS_TOKEN
        - OCCSON_PASSPHRASE
        - RAILS_MASTER_KEY
        - RAILS_ASSET_HOST
    container_name: aldwin7894-app
    image: aldwin7894/aldwin7894:prod
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/${MONGO_DB}
      - REDIS_URL=redis://redis:6379
      - TZ=Asia/Manila
      - RAILS_MASTER_KEY
      - RAILS_ENV
      - NODE_ENV
      - RAILS_ASSET_HOST
      - OCCSON_ACCESS_TOKEN
      - OCCSON_PASSPHRASE
    # healthcheck:
    #   test: wget -nv -t1 --spider http://web:3000/healthcheck || exit 1
    #   interval: 5m
    #   timeout: 10s
    #   retries: 5
    #   start_period: 10s

volumes:
  # trunk-ignore(yamllint/empty-values)
  dbdata:
  # trunk-ignore(yamllint/empty-values)
  redis:

secrets:
  TZ:
    environment: TZ
  RAILS_ENV:
    environment: RAILS_ENV
  NODE_ENV:
    environment: NODE_ENV
  OCCSON_ACCESS_TOKEN:
    environment: OCCSON_ACCESS_TOKEN
  OCCSON_PASSPHRASE:
    environment: OCCSON_PASSPHRASE
  RAILS_MASTER_KEY:
    environment: RAILS_MASTER_KEY
  RAILS_ASSET_HOST:
    environment: RAILS_ASSET_HOST
