version: "3.9"

services:
  db:
    container_name: project-cyan-mongo
    image: mongo:4.4.6
    restart: always
    environment:
      - TZ
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
  redis:
    container_name: project-cyan-redis
    build:
      context: ./config/redis/
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    environment:
      - TZ
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  redisinsight:
    container_name: project-cyan-redisinsight
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db

  web:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - TZ
        - RAILS_ENV
        - NODE_ENV
        - OCCSON_ACCESS_TOKEN
        - OCCSON_PASSPHRASE
        - RAILS_MASTER_KEY
        - RAILS_ASSET_HOST
    container_name: project-cyan-app
    image: aldwin7894/project-cyan:prod
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/${MONGO_DB}
      - REDIS_URL=redis://redis:6379
      - TZ=Asia/Manila
      - RAILS_MASTER_KEY
      - RAILS_ENV
      - NODE_ENV
      - RAILS_ASSET_HOST
      - OCCSON_ACCESS_TOKEN
      - OCCSON_PASSPHRASE

volumes:
  dbdata:
  redis:
  redisinsight:

secrets:
  TZ:
    environment: TZ
  RAILS_ENV:
    environment: RAILS_ENV
  NODE_ENV:
    environment: NODE_ENV
  OCCSON_ACCESS_TOKEN:
    environment: OCCSON_ACCESS_TOKEN
  OCCSON_PASSPHRASE:
    environment: OCCSON_PASSPHRASE
  RAILS_MASTER_KEY:
    environment: RAILS_MASTER_KEY
  RAILS_ASSET_HOST:
    environment: RAILS_ASSET_HOST
