version: "3.9"

services:
  db:
    container_name: aldwin7894-pg
    image: postgres:14-alpine
    restart: always
    user: postgres
    environment:
      - TZ
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    container_name: aldwin7894-redis
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    environment:
      - TZ
    ports:
      - 6379:6379
    volumes:
      - redis:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TZ_ARG=${TZ}
        - RAILS_ENV_ARG=${RAILS_ENV}
        - NODE_ENV_ARG=${NODE_ENV}
        - OCCSON_ACCESS_TOKEN_ARG=${OCCSON_ACCESS_TOKEN}
        - OCCSON_PASSPHRASE_ARG=${OCCSON_PASSPHRASE}
        - RAILS_MASTER_KEY_ARG=${RAILS_MASTER_KEY}
        - RAILS_ASSET_HOST_ARG=${RAILS_ASSET_HOST}
    container_name: aldwin7894-app
    image: aldwin7894/aldwin7894:prod
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - TZ=Asia/Manila
      - RAILS_MASTER_KEY
      - RAILS_ENV
      - NODE_ENV
      - RAILS_ASSET_HOST
      - OCCSON_ACCESS_TOKEN
      - OCCSON_PASSPHRASE
    # healthcheck:
    #   test: wget -nv -t1 --spider http://web:3000/healthcheck || exit 1
    #   interval: 5m
    #   timeout: 10s
    #   retries: 5
    #   start_period: 10s

volumes:
  dbdata:
  redis:
