version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - TZ
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file: .env
  redis:
    image: redis:latest
    command: redis-server
    restart: always
    environment:
      - TZ
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'
    env_file: .env
  web:
    build: .
    container_name: aldwin7894
    image: aldwin7894/aldwin7894:prod
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    environment:
      - "DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      - REDIS_URL=redis://redis:6379
      - TZ
      - RAILS_MASTER_KEY
      - RAILS_ENV
      - NODE_ENV
      - RAILS_ASSET_HOST
    volumes:
      - .:/app
      - ruby-gems:/gems
    env_file: .env

volumes:
  dbdata:
  redis:
  ruby-gems:
