# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `User`.
# Please instead update this file by running `bin/tapioca dsl User`.


class User
  sig { returns(T.untyped) }
  def password_confirmation; end

  sig { params(password_confirmation: T.untyped).returns(T.untyped) }
  def password_confirmation=(password_confirmation); end
end
