pngout: false
svgo: false
advpng:
  level: 3
gifsicle:
  level: 2
  careful: true
jpegoptim:
  allow_lossy: true
  max_quality: 80
jpegrecompress:
  allow_lossy: true
  quality: 2
optipng:
  level: 5
