# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::RequireHooks::LoadIseq; end
module ActiveRecord::ConnectionAdapters::DatabaseStatements; end
module ActiveRecord::ConnectionAdapters::SchemaStatements; end
module Set::SubclassCompatible; end
module Set::SubclassCompatible::ClassMethods; end
module ::ERB::Escape; end
