# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mongoid::Timestamps`.
# Please instead update this file by running `bin/tapioca dsl Mongoid::Timestamps`.

module Mongoid::Timestamps
  mixes_in_class_methods ::Mongoid::Timestamps::Created::ClassMethods
  mixes_in_class_methods ::Mongoid::Timestamps::Updated::ClassMethods
end
