# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mongoid::Traversable`.
# Please instead update this file by running `bin/tapioca dsl Mongoid::Traversable`.

module Mongoid::Traversable
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods

  module GeneratedClassMethods
    def discriminator_key; end
    def discriminator_key=(value); end
    def discriminator_key?; end
  end

  module GeneratedInstanceMethods; end
end
