# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Protobuf::FeatureSet::StringFieldValidation`.
# Please instead update this file by running `bin/tapioca dsl Google::Protobuf::FeatureSet::StringFieldValidation`.

module Google::Protobuf::FeatureSet::StringFieldValidation
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Google::Protobuf::FeatureSet::StringFieldValidation::HINT = 2
Google::Protobuf::FeatureSet::StringFieldValidation::MANDATORY = 1
Google::Protobuf::FeatureSet::StringFieldValidation::NONE = 3
Google::Protobuf::FeatureSet::StringFieldValidation::STRING_FIELD_VALIDATION_UNKNOWN = 0
