# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mongoid::Timestamps::Short`.
# Please instead update this file by running `bin/tapioca dsl Mongoid::Timestamps::Short`.

module Mongoid::Timestamps::Short
  mixes_in_class_methods ::Mongoid::Timestamps::Created::Short::ClassMethods
  mixes_in_class_methods ::Mongoid::Timestamps::Updated::Short::ClassMethods
end
