# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionController::Instrumentation`.
# Please instead update this file by running `bin/tapioca dsl ActionController::Instrumentation`.

module ActionController::Instrumentation
  mixes_in_class_methods ::AbstractController::Logger::ClassMethods
end
