name: Docker Image CI
permissions: read-all
concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [master]

jobs:
  docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - id: docker-build
        name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: aldwin7894/project-cyan:prod
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          secrets: |
            TZ=${{ secrets.TZ }}
            RAILS_ENV=${{ secrets.RAILS_ENV }}
            NODE_ENV=${{ secrets.NODE_ENV }}
            RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
            RAILS_ASSET_HOST=${{ secrets.RAILS_ASSET_HOST }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
