name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - id: docker-publish
        name: Build image
        uses: bitovi/github-actions-docker-publish@main
        with:
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          checkout: 'false'
          image_tag: prod
          org_name: aldwin7894
          repo_name: aldwin7894
          build_args: --build-arg TZ_ARG="Asia/Manila" --build-arg RAILS_ENV_ARG="production" --build-arg NODE_ENV_ARG="production" --build-arg OCCSON_ACCESS_TOKEN_ARG=${{ secrets.OCCSON_ACCESS_TOKEN }} --build-arg OCCSON_PASSPHRASE_ARG=${{ secrets.OCCSON_PASSPHRASE }} --build-arg RAILS_MASTER_KEY_ARG=${{ secrets.RAILS_MASTER_KEY }} --build-arg RAILS_ASSET_HOST_ARG=${{ secrets.RAILS_ASSET_HOST }}
          working-directory: .
      - run: |
          echo "Image Created:  ${{ env.image }}"
          echo "Tag Created: ${{ env.tag }}"
