name: Trunk Check
run-name: Trunk Check
permissions: read-all

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  trunk-check:
    name: Trunk Check
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          cache: true
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
          setup-deps: true
          save-annotations: true
