name: Trunk Check
run-name: Trunk Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  trunk-check:
    name: Trunk Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: [3.2.2]
        node: [18.12.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install Node Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          cache: true
